#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 101
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum {
  anon_sym_LF = 1,
  anon_sym_SEMI = 2,
  sym_comment = 3,
  sym__word_content = 4,
  sym_escape_sequence = 5,
  sym_variable_substitution = 6,
  anon_sym_DQUOTE = 7,
  sym__quoted_word_content = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  sym__concat = 13,
  sym_source_file = 14,
  sym__statement = 15,
  sym_command = 16,
  sym_word_list = 17,
  sym__word = 18,
  sym_concatenation = 19,
  sym_word = 20,
  sym_quoted_word = 21,
  sym_braced_word = 22,
  sym_command_substitution = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym_word_list_repeat1 = 25,
  aux_sym_concatenation_repeat1 = 26,
  aux_sym_word_repeat1 = 27,
  aux_sym_quoted_word_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_comment] = "comment",
  [sym__word_content] = "_word_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_variable_substitution] = "variable_substitution",
  [anon_sym_DQUOTE] = "\"",
  [sym__quoted_word_content] = "_quoted_word_content",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym__concat] = "_concat",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_command] = "command",
  [sym_word_list] = "word_list",
  [sym__word] = "_word",
  [sym_concatenation] = "concatenation",
  [sym_word] = "word",
  [sym_quoted_word] = "quoted_word",
  [sym_braced_word] = "braced_word",
  [sym_command_substitution] = "command_substitution",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_word_list_repeat1] = "word_list_repeat1",
  [aux_sym_concatenation_repeat1] = "concatenation_repeat1",
  [aux_sym_word_repeat1] = "word_repeat1",
  [aux_sym_quoted_word_repeat1] = "quoted_word_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_comment] = sym_comment,
  [sym__word_content] = sym__word_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_variable_substitution] = sym_variable_substitution,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__quoted_word_content] = sym__quoted_word_content,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym__concat] = sym__concat,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_command] = sym_command,
  [sym_word_list] = sym_word_list,
  [sym__word] = sym__word,
  [sym_concatenation] = sym_concatenation,
  [sym_word] = sym_word,
  [sym_quoted_word] = sym_quoted_word,
  [sym_braced_word] = sym_braced_word,
  [sym_command_substitution] = sym_command_substitution,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_word_list_repeat1] = aux_sym_word_list_repeat1,
  [aux_sym_concatenation_repeat1] = aux_sym_concatenation_repeat1,
  [aux_sym_word_repeat1] = aux_sym_word_repeat1,
  [aux_sym_quoted_word_repeat1] = aux_sym_quoted_word_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__word_content] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_substitution] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__quoted_word_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym__concat] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_word_list] = {
    .visible = true,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym_concatenation] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_word] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_word] = {
    .visible = true,
    .named = true,
  },
  [sym_command_substitution] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_concatenation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_word_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_arguments, 1},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static inline bool sym_comment_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < ' '
      ? (c < '\r'
        ? c == '\t'
        : c <= '\r')
      : (c <= ' ' || c == '"'))
    : (c <= '$' || (c < '{'
      ? (c < '['
        ? c == ';'
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static inline bool sym__word_content_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '"'
        ? c == ' '
        : c <= '"')))
    : (c <= '$' || (c < '{'
      ? (c < '['
        ? c == ';'
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(15);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '$') ADVANCE(3);
      if (lookahead == ';') ADVANCE(8);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(15);
      if (lookahead == '$') ADVANCE(3);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != ';' &&
          lookahead != ']') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(15);
      if (lookahead == '$') ADVANCE(3);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(17);
      END_STATE();
    case 3:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '"') ADVANCE(15);
      if (lookahead == '$') ADVANCE(3);
      if (lookahead == ';') ADVANCE(8);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(12);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_comment);
      if (sym_comment_character_set_1(lookahead)) ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__word_content);
      if (sym_comment_character_set_1(lookahead)) ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__word_content);
      if (!sym__word_content_character_set_1(lookahead)) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_variable_substitution);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__quoted_word_content);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__quoted_word_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 5, .external_lex_state = 1},
  [27] = {.lex_state = 5, .external_lex_state = 1},
  [28] = {.lex_state = 5, .external_lex_state = 1},
  [29] = {.lex_state = 5, .external_lex_state = 1},
  [30] = {.lex_state = 5, .external_lex_state = 1},
  [31] = {.lex_state = 5, .external_lex_state = 1},
  [32] = {.lex_state = 5, .external_lex_state = 1},
  [33] = {.lex_state = 5, .external_lex_state = 1},
  [34] = {.lex_state = 5, .external_lex_state = 1},
  [35] = {.lex_state = 5, .external_lex_state = 1},
  [36] = {.lex_state = 5, .external_lex_state = 1},
  [37] = {.lex_state = 5, .external_lex_state = 1},
  [38] = {.lex_state = 5, .external_lex_state = 1},
  [39] = {.lex_state = 5, .external_lex_state = 1},
  [40] = {.lex_state = 5, .external_lex_state = 1},
  [41] = {.lex_state = 5, .external_lex_state = 1},
  [42] = {.lex_state = 1, .external_lex_state = 1},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 1, .external_lex_state = 1},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 1, .external_lex_state = 1},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 1, .external_lex_state = 1},
  [57] = {.lex_state = 1, .external_lex_state = 1},
  [58] = {.lex_state = 1, .external_lex_state = 1},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1, .external_lex_state = 1},
  [62] = {.lex_state = 1, .external_lex_state = 1},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 5},
  [92] = {.lex_state = 5},
  [93] = {.lex_state = 5},
  [94] = {.lex_state = 5},
  [95] = {.lex_state = 5},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 5},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 0},
};

enum {
  ts_external_token__concat = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__concat] = sym__concat,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__concat] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__word_content] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_variable_substitution] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym__concat] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(100),
    [sym__statement] = STATE(91),
    [sym_command] = STATE(91),
    [sym__word] = STATE(9),
    [sym_concatenation] = STATE(9),
    [sym_word] = STATE(30),
    [sym_quoted_word] = STATE(9),
    [sym_braced_word] = STATE(9),
    [sym_command_substitution] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym__word_content] = ACTIONS(7),
    [sym_escape_sequence] = ACTIONS(9),
    [sym_variable_substitution] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
  },
  [2] = {
    [sym__statement] = STATE(84),
    [sym_command] = STATE(84),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_comment] = ACTIONS(19),
    [sym__word_content] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_variable_substitution] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(33),
  },
  [3] = {
    [sym__statement] = STATE(89),
    [sym_command] = STATE(89),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_comment] = ACTIONS(35),
    [sym__word_content] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_variable_substitution] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(37),
  },
  [4] = {
    [sym__statement] = STATE(93),
    [sym_command] = STATE(93),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_comment] = ACTIONS(39),
    [sym__word_content] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_variable_substitution] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(41),
  },
  [5] = {
    [sym__statement] = STATE(95),
    [sym_command] = STATE(95),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_comment] = ACTIONS(45),
    [sym__word_content] = ACTIONS(48),
    [sym_escape_sequence] = ACTIONS(51),
    [sym_variable_substitution] = ACTIONS(54),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(60),
    [anon_sym_LBRACK] = ACTIONS(63),
  },
  [6] = {
    [sym__statement] = STATE(83),
    [sym_command] = STATE(83),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_comment] = ACTIONS(66),
    [sym__word_content] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_variable_substitution] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(68),
  },
  [7] = {
    [sym__statement] = STATE(92),
    [sym_command] = STATE(92),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(70),
    [sym__word_content] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_variable_substitution] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(72),
  },
  [8] = {
    [sym__statement] = STATE(90),
    [sym_command] = STATE(90),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_comment] = ACTIONS(74),
    [sym__word_content] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_variable_substitution] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(76),
  },
  [9] = {
    [sym_word_list] = STATE(88),
    [sym__word] = STATE(17),
    [sym_concatenation] = STATE(17),
    [sym_word] = STATE(30),
    [sym_quoted_word] = STATE(17),
    [sym_braced_word] = STATE(17),
    [sym_command_substitution] = STATE(17),
    [aux_sym_word_list_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(78),
    [anon_sym_LF] = ACTIONS(78),
    [anon_sym_SEMI] = ACTIONS(80),
    [sym__word_content] = ACTIONS(7),
    [sym_escape_sequence] = ACTIONS(7),
    [sym_variable_substitution] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(86),
    [anon_sym_LBRACK] = ACTIONS(88),
  },
  [10] = {
    [sym__statement] = STATE(85),
    [sym_command] = STATE(85),
    [sym__word] = STATE(9),
    [sym_concatenation] = STATE(9),
    [sym_word] = STATE(30),
    [sym_quoted_word] = STATE(9),
    [sym_braced_word] = STATE(9),
    [sym_command_substitution] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(90),
    [sym_comment] = ACTIONS(92),
    [sym__word_content] = ACTIONS(7),
    [sym_escape_sequence] = ACTIONS(9),
    [sym_variable_substitution] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
  },
  [11] = {
    [sym__statement] = STATE(87),
    [sym_command] = STATE(87),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_comment] = ACTIONS(94),
    [sym__word_content] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_variable_substitution] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(96),
  },
  [12] = {
    [sym__statement] = STATE(97),
    [sym_command] = STATE(97),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_comment] = ACTIONS(98),
    [sym__word_content] = ACTIONS(48),
    [sym_escape_sequence] = ACTIONS(51),
    [sym_variable_substitution] = ACTIONS(54),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(60),
    [anon_sym_LBRACK] = ACTIONS(63),
    [anon_sym_RBRACK] = ACTIONS(43),
  },
  [13] = {
    [sym__statement] = STATE(86),
    [sym_command] = STATE(86),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(11),
    [sym_comment] = ACTIONS(101),
    [sym__word_content] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_variable_substitution] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(103),
  },
  [14] = {
    [sym_word_list] = STATE(94),
    [sym__word] = STATE(18),
    [sym_concatenation] = STATE(18),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(18),
    [sym_braced_word] = STATE(18),
    [sym_command_substitution] = STATE(18),
    [aux_sym_word_list_repeat1] = STATE(18),
    [anon_sym_LF] = ACTIONS(78),
    [anon_sym_SEMI] = ACTIONS(80),
    [sym__word_content] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(21),
    [sym_variable_substitution] = ACTIONS(105),
    [anon_sym_DQUOTE] = ACTIONS(107),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(111),
    [anon_sym_RBRACK] = ACTIONS(80),
  },
  [15] = {
    [sym__word] = STATE(15),
    [sym_concatenation] = STATE(15),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(15),
    [sym_braced_word] = STATE(15),
    [sym_command_substitution] = STATE(15),
    [aux_sym_word_list_repeat1] = STATE(15),
    [anon_sym_LF] = ACTIONS(113),
    [anon_sym_SEMI] = ACTIONS(115),
    [sym__word_content] = ACTIONS(117),
    [sym_escape_sequence] = ACTIONS(117),
    [sym_variable_substitution] = ACTIONS(120),
    [anon_sym_DQUOTE] = ACTIONS(123),
    [anon_sym_LBRACE] = ACTIONS(126),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_RBRACK] = ACTIONS(115),
  },
  [16] = {
    [sym__word] = STATE(16),
    [sym_concatenation] = STATE(16),
    [sym_word] = STATE(30),
    [sym_quoted_word] = STATE(16),
    [sym_braced_word] = STATE(16),
    [sym_command_substitution] = STATE(16),
    [aux_sym_word_list_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(113),
    [anon_sym_LF] = ACTIONS(113),
    [anon_sym_SEMI] = ACTIONS(115),
    [sym__word_content] = ACTIONS(132),
    [sym_escape_sequence] = ACTIONS(132),
    [sym_variable_substitution] = ACTIONS(135),
    [anon_sym_DQUOTE] = ACTIONS(138),
    [anon_sym_LBRACE] = ACTIONS(141),
    [anon_sym_LBRACK] = ACTIONS(144),
  },
  [17] = {
    [sym__word] = STATE(16),
    [sym_concatenation] = STATE(16),
    [sym_word] = STATE(30),
    [sym_quoted_word] = STATE(16),
    [sym_braced_word] = STATE(16),
    [sym_command_substitution] = STATE(16),
    [aux_sym_word_list_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(147),
    [anon_sym_LF] = ACTIONS(147),
    [anon_sym_SEMI] = ACTIONS(149),
    [sym__word_content] = ACTIONS(7),
    [sym_escape_sequence] = ACTIONS(7),
    [sym_variable_substitution] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(86),
    [anon_sym_LBRACK] = ACTIONS(88),
  },
  [18] = {
    [sym__word] = STATE(15),
    [sym_concatenation] = STATE(15),
    [sym_word] = STATE(36),
    [sym_quoted_word] = STATE(15),
    [sym_braced_word] = STATE(15),
    [sym_command_substitution] = STATE(15),
    [aux_sym_word_list_repeat1] = STATE(15),
    [anon_sym_LF] = ACTIONS(147),
    [anon_sym_SEMI] = ACTIONS(149),
    [sym__word_content] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(21),
    [sym_variable_substitution] = ACTIONS(105),
    [anon_sym_DQUOTE] = ACTIONS(107),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(111),
    [anon_sym_RBRACK] = ACTIONS(149),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(153), 1,
      sym_variable_substitution,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    ACTIONS(161), 1,
      anon_sym_LBRACK,
    STATE(56), 1,
      sym_word,
    ACTIONS(151), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(24), 6,
      sym__word,
      sym_concatenation,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [31] = 8,
    ACTIONS(153), 1,
      sym_variable_substitution,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      anon_sym_LBRACK,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      sym_word,
    ACTIONS(151), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(22), 6,
      sym__word,
      sym_concatenation,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [62] = 8,
    ACTIONS(153), 1,
      sym_variable_substitution,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      anon_sym_LBRACK,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      sym_word,
    ACTIONS(151), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(22), 6,
      sym__word,
      sym_concatenation,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [93] = 8,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    ACTIONS(170), 1,
      sym_variable_substitution,
    ACTIONS(173), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    ACTIONS(179), 1,
      anon_sym_LBRACK,
    STATE(56), 1,
      sym_word,
    ACTIONS(167), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(22), 6,
      sym__word,
      sym_concatenation,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [124] = 8,
    ACTIONS(153), 1,
      sym_variable_substitution,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      anon_sym_LBRACK,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      sym_word,
    ACTIONS(151), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(21), 6,
      sym__word,
      sym_concatenation,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [155] = 8,
    ACTIONS(153), 1,
      sym_variable_substitution,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      sym_word,
    ACTIONS(151), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(22), 6,
      sym__word,
      sym_concatenation,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [186] = 8,
    ACTIONS(153), 1,
      sym_variable_substitution,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      anon_sym_LBRACK,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      sym_word,
    ACTIONS(151), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(20), 6,
      sym__word,
      sym_concatenation,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [217] = 4,
    ACTIONS(192), 1,
      sym__concat,
    STATE(27), 1,
      aux_sym_word_repeat1,
    ACTIONS(188), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(190), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [237] = 4,
    ACTIONS(199), 1,
      sym__concat,
    STATE(27), 1,
      aux_sym_word_repeat1,
    ACTIONS(195), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(197), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [257] = 4,
    ACTIONS(206), 1,
      sym__concat,
    STATE(28), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(202), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(204), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [277] = 4,
    ACTIONS(195), 1,
      anon_sym_LF,
    ACTIONS(209), 1,
      sym__concat,
    STATE(29), 1,
      aux_sym_word_repeat1,
    ACTIONS(197), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [297] = 4,
    ACTIONS(216), 1,
      sym__concat,
    STATE(37), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(212), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(214), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [317] = 4,
    ACTIONS(218), 1,
      anon_sym_LF,
    ACTIONS(222), 1,
      sym__concat,
    STATE(34), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(220), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [337] = 4,
    ACTIONS(188), 1,
      anon_sym_LF,
    ACTIONS(224), 1,
      sym__concat,
    STATE(29), 1,
      aux_sym_word_repeat1,
    ACTIONS(190), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [357] = 4,
    ACTIONS(227), 1,
      anon_sym_LF,
    ACTIONS(231), 1,
      sym__concat,
    STATE(32), 1,
      aux_sym_word_repeat1,
    ACTIONS(229), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [377] = 4,
    ACTIONS(202), 1,
      anon_sym_LF,
    ACTIONS(234), 1,
      sym__concat,
    STATE(34), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(204), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [397] = 4,
    ACTIONS(237), 1,
      sym__concat,
    STATE(26), 1,
      aux_sym_word_repeat1,
    ACTIONS(227), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(229), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [417] = 4,
    ACTIONS(212), 1,
      anon_sym_LF,
    ACTIONS(222), 1,
      sym__concat,
    STATE(31), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(214), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [437] = 4,
    ACTIONS(216), 1,
      sym__concat,
    STATE(28), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(218), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(220), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [457] = 2,
    ACTIONS(202), 3,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(204), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [472] = 2,
    ACTIONS(202), 2,
      sym__concat,
      anon_sym_LF,
    ACTIONS(204), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [487] = 2,
    ACTIONS(240), 2,
      sym__concat,
      anon_sym_LF,
    ACTIONS(242), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [502] = 2,
    ACTIONS(240), 3,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(242), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [517] = 3,
    ACTIONS(244), 1,
      sym__concat,
    STATE(42), 1,
      aux_sym_word_repeat1,
    ACTIONS(195), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [533] = 2,
    ACTIONS(247), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(249), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [547] = 2,
    ACTIONS(247), 1,
      anon_sym_LF,
    ACTIONS(249), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [561] = 3,
    ACTIONS(251), 1,
      sym__concat,
    STATE(53), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(218), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [577] = 2,
    ACTIONS(253), 1,
      anon_sym_LF,
    ACTIONS(255), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [591] = 2,
    ACTIONS(257), 1,
      anon_sym_LF,
    ACTIONS(259), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [605] = 2,
    ACTIONS(261), 1,
      anon_sym_LF,
    ACTIONS(263), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [619] = 2,
    ACTIONS(261), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(263), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [633] = 2,
    ACTIONS(257), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(259), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [647] = 2,
    ACTIONS(265), 1,
      anon_sym_LF,
    ACTIONS(267), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [661] = 2,
    ACTIONS(269), 1,
      anon_sym_LF,
    ACTIONS(271), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [675] = 3,
    ACTIONS(273), 1,
      sym__concat,
    STATE(53), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(202), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [691] = 2,
    ACTIONS(253), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(255), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [705] = 2,
    ACTIONS(265), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(267), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [719] = 3,
    ACTIONS(251), 1,
      sym__concat,
    STATE(45), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(212), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [735] = 3,
    ACTIONS(276), 1,
      sym__concat,
    STATE(42), 1,
      aux_sym_word_repeat1,
    ACTIONS(188), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [751] = 3,
    ACTIONS(279), 1,
      sym__concat,
    STATE(57), 1,
      aux_sym_word_repeat1,
    ACTIONS(227), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [767] = 2,
    ACTIONS(269), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(271), 7,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [781] = 2,
    ACTIONS(282), 1,
      sym__word_content,
    ACTIONS(43), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [794] = 1,
    ACTIONS(202), 8,
      sym__concat,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [805] = 1,
    ACTIONS(240), 8,
      sym__concat,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [816] = 2,
    ACTIONS(282), 1,
      sym__word_content,
    ACTIONS(43), 7,
      sym_comment,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [829] = 5,
    ACTIONS(286), 1,
      anon_sym_DQUOTE,
    ACTIONS(288), 1,
      sym__quoted_word_content,
    ACTIONS(290), 1,
      anon_sym_LBRACK,
    ACTIONS(284), 2,
      sym_escape_sequence,
      sym_variable_substitution,
    STATE(69), 2,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [847] = 1,
    ACTIONS(257), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [857] = 1,
    ACTIONS(261), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [867] = 5,
    ACTIONS(288), 1,
      sym__quoted_word_content,
    ACTIONS(290), 1,
      anon_sym_LBRACK,
    ACTIONS(292), 1,
      anon_sym_DQUOTE,
    ACTIONS(284), 2,
      sym_escape_sequence,
      sym_variable_substitution,
    STATE(69), 2,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [885] = 1,
    ACTIONS(253), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [895] = 5,
    ACTIONS(297), 1,
      anon_sym_DQUOTE,
    ACTIONS(299), 1,
      sym__quoted_word_content,
    ACTIONS(302), 1,
      anon_sym_LBRACK,
    ACTIONS(294), 2,
      sym_escape_sequence,
      sym_variable_substitution,
    STATE(69), 2,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [913] = 5,
    ACTIONS(288), 1,
      sym__quoted_word_content,
    ACTIONS(290), 1,
      anon_sym_LBRACK,
    ACTIONS(305), 1,
      anon_sym_DQUOTE,
    ACTIONS(284), 2,
      sym_escape_sequence,
      sym_variable_substitution,
    STATE(69), 2,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [931] = 1,
    ACTIONS(247), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [941] = 1,
    ACTIONS(265), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [951] = 1,
    ACTIONS(269), 7,
      sym__word_content,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
  [961] = 4,
    ACTIONS(290), 1,
      anon_sym_LBRACK,
    ACTIONS(309), 1,
      sym__quoted_word_content,
    ACTIONS(307), 2,
      sym_escape_sequence,
      sym_variable_substitution,
    STATE(64), 2,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [976] = 4,
    ACTIONS(290), 1,
      anon_sym_LBRACK,
    ACTIONS(313), 1,
      sym__quoted_word_content,
    ACTIONS(311), 2,
      sym_escape_sequence,
      sym_variable_substitution,
    STATE(67), 2,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [991] = 4,
    ACTIONS(290), 1,
      anon_sym_LBRACK,
    ACTIONS(317), 1,
      sym__quoted_word_content,
    ACTIONS(315), 2,
      sym_escape_sequence,
      sym_variable_substitution,
    STATE(70), 2,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [1006] = 2,
    ACTIONS(247), 1,
      sym__quoted_word_content,
    ACTIONS(249), 4,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1016] = 2,
    ACTIONS(253), 1,
      sym__quoted_word_content,
    ACTIONS(255), 4,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1026] = 2,
    ACTIONS(265), 1,
      sym__quoted_word_content,
    ACTIONS(267), 4,
      sym_escape_sequence,
      sym_variable_substitution,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1036] = 3,
    ACTIONS(319), 1,
      sym_variable_substitution,
    STATE(39), 1,
      sym_word,
    ACTIONS(23), 2,
      sym__word_content,
      sym_escape_sequence,
  [1047] = 3,
    ACTIONS(321), 1,
      sym_variable_substitution,
    STATE(61), 1,
      sym_word,
    ACTIONS(151), 2,
      sym__word_content,
      sym_escape_sequence,
  [1058] = 3,
    ACTIONS(323), 1,
      sym_variable_substitution,
    STATE(38), 1,
      sym_word,
    ACTIONS(9), 2,
      sym__word_content,
      sym_escape_sequence,
  [1069] = 3,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(327), 1,
      anon_sym_SEMI,
    ACTIONS(329), 1,
      anon_sym_RBRACK,
  [1079] = 3,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(327), 1,
      anon_sym_SEMI,
    ACTIONS(331), 1,
      anon_sym_RBRACK,
  [1089] = 3,
    ACTIONS(333), 1,
      ts_builtin_sym_end,
    ACTIONS(335), 1,
      anon_sym_LF,
    ACTIONS(337), 1,
      anon_sym_SEMI,
  [1099] = 3,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(327), 1,
      anon_sym_SEMI,
    ACTIONS(339), 1,
      anon_sym_RBRACK,
  [1109] = 3,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(327), 1,
      anon_sym_SEMI,
    ACTIONS(341), 1,
      anon_sym_RBRACK,
  [1119] = 2,
    ACTIONS(345), 1,
      anon_sym_SEMI,
    ACTIONS(343), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1127] = 3,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(327), 1,
      anon_sym_SEMI,
    ACTIONS(347), 1,
      anon_sym_RBRACK,
  [1137] = 3,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(327), 1,
      anon_sym_SEMI,
    ACTIONS(349), 1,
      anon_sym_RBRACK,
  [1147] = 3,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(335), 1,
      anon_sym_LF,
    ACTIONS(337), 1,
      anon_sym_SEMI,
  [1157] = 3,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(327), 1,
      anon_sym_SEMI,
    ACTIONS(351), 1,
      anon_sym_RBRACK,
  [1167] = 3,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(327), 1,
      anon_sym_SEMI,
    ACTIONS(353), 1,
      anon_sym_RBRACK,
  [1177] = 2,
    ACTIONS(343), 1,
      anon_sym_LF,
    ACTIONS(345), 2,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1185] = 2,
    ACTIONS(335), 1,
      anon_sym_LF,
    ACTIONS(337), 1,
      anon_sym_SEMI,
  [1192] = 1,
    ACTIONS(355), 2,
      sym__word_content,
      sym_escape_sequence,
  [1197] = 2,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(327), 1,
      anon_sym_SEMI,
  [1204] = 1,
    ACTIONS(357), 2,
      sym__word_content,
      sym_escape_sequence,
  [1209] = 1,
    ACTIONS(359), 2,
      sym__word_content,
      sym_escape_sequence,
  [1214] = 1,
    ACTIONS(361), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 31,
  [SMALL_STATE(21)] = 62,
  [SMALL_STATE(22)] = 93,
  [SMALL_STATE(23)] = 124,
  [SMALL_STATE(24)] = 155,
  [SMALL_STATE(25)] = 186,
  [SMALL_STATE(26)] = 217,
  [SMALL_STATE(27)] = 237,
  [SMALL_STATE(28)] = 257,
  [SMALL_STATE(29)] = 277,
  [SMALL_STATE(30)] = 297,
  [SMALL_STATE(31)] = 317,
  [SMALL_STATE(32)] = 337,
  [SMALL_STATE(33)] = 357,
  [SMALL_STATE(34)] = 377,
  [SMALL_STATE(35)] = 397,
  [SMALL_STATE(36)] = 417,
  [SMALL_STATE(37)] = 437,
  [SMALL_STATE(38)] = 457,
  [SMALL_STATE(39)] = 472,
  [SMALL_STATE(40)] = 487,
  [SMALL_STATE(41)] = 502,
  [SMALL_STATE(42)] = 517,
  [SMALL_STATE(43)] = 533,
  [SMALL_STATE(44)] = 547,
  [SMALL_STATE(45)] = 561,
  [SMALL_STATE(46)] = 577,
  [SMALL_STATE(47)] = 591,
  [SMALL_STATE(48)] = 605,
  [SMALL_STATE(49)] = 619,
  [SMALL_STATE(50)] = 633,
  [SMALL_STATE(51)] = 647,
  [SMALL_STATE(52)] = 661,
  [SMALL_STATE(53)] = 675,
  [SMALL_STATE(54)] = 691,
  [SMALL_STATE(55)] = 705,
  [SMALL_STATE(56)] = 719,
  [SMALL_STATE(57)] = 735,
  [SMALL_STATE(58)] = 751,
  [SMALL_STATE(59)] = 767,
  [SMALL_STATE(60)] = 781,
  [SMALL_STATE(61)] = 794,
  [SMALL_STATE(62)] = 805,
  [SMALL_STATE(63)] = 816,
  [SMALL_STATE(64)] = 829,
  [SMALL_STATE(65)] = 847,
  [SMALL_STATE(66)] = 857,
  [SMALL_STATE(67)] = 867,
  [SMALL_STATE(68)] = 885,
  [SMALL_STATE(69)] = 895,
  [SMALL_STATE(70)] = 913,
  [SMALL_STATE(71)] = 931,
  [SMALL_STATE(72)] = 941,
  [SMALL_STATE(73)] = 951,
  [SMALL_STATE(74)] = 961,
  [SMALL_STATE(75)] = 976,
  [SMALL_STATE(76)] = 991,
  [SMALL_STATE(77)] = 1006,
  [SMALL_STATE(78)] = 1016,
  [SMALL_STATE(79)] = 1026,
  [SMALL_STATE(80)] = 1036,
  [SMALL_STATE(81)] = 1047,
  [SMALL_STATE(82)] = 1058,
  [SMALL_STATE(83)] = 1069,
  [SMALL_STATE(84)] = 1079,
  [SMALL_STATE(85)] = 1089,
  [SMALL_STATE(86)] = 1099,
  [SMALL_STATE(87)] = 1109,
  [SMALL_STATE(88)] = 1119,
  [SMALL_STATE(89)] = 1127,
  [SMALL_STATE(90)] = 1137,
  [SMALL_STATE(91)] = 1147,
  [SMALL_STATE(92)] = 1157,
  [SMALL_STATE(93)] = 1167,
  [SMALL_STATE(94)] = 1177,
  [SMALL_STATE(95)] = 1185,
  [SMALL_STATE(96)] = 1192,
  [SMALL_STATE(97)] = 1197,
  [SMALL_STATE(98)] = 1204,
  [SMALL_STATE(99)] = 1209,
  [SMALL_STATE(100)] = 1214,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(95),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(33),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(33),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(76),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(19),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, .production_id = 1),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, .production_id = 1),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(97),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(33),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(36),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(76),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(19),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(7),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(35),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(30),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(74),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(25),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(6),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word_list, 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word_list, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(58),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(56),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(75),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(23),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(3),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 2),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 2),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 2), SHIFT(98),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(98),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_concatenation_repeat1, 2),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2), SHIFT_REPEAT(82),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(96),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__word, 1),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__word, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concatenation, 2),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_concatenation, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 2), SHIFT(96),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 1), SHIFT(96),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2), SHIFT_REPEAT(80),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 1), SHIFT(98),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2, .dynamic_precedence = 1),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2, .dynamic_precedence = 1),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(99),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 3),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 3),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 2),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 2),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_word, 3),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_word, 3),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_word, 3),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_word, 3),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 4),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 4),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_word, 2),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_word, 2),
  [273] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2), SHIFT_REPEAT(81),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 2), SHIFT(99),
  [279] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 1), SHIFT(99),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [284] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [286] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [292] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [294] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(69),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2),
  [299] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(69),
  [302] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(13),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [315] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [327] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [329] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [331] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [337] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [339] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [341] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, .production_id = 2),
  [345] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, .production_id = 2),
  [347] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [349] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [351] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [353] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [361] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_tcl_external_scanner_create(void);
void tree_sitter_tcl_external_scanner_destroy(void *);
bool tree_sitter_tcl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_tcl_external_scanner_serialize(void *, char *);
void tree_sitter_tcl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tcl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_tcl_external_scanner_create,
      tree_sitter_tcl_external_scanner_destroy,
      tree_sitter_tcl_external_scanner_scan,
      tree_sitter_tcl_external_scanner_serialize,
      tree_sitter_tcl_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
