#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 26
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum {
  sym__word_content = 1,
  anon_sym_LF = 2,
  anon_sym_SEMI = 3,
  sym_comment = 4,
  sym_escape_sequence = 5,
  anon_sym_DOLLAR = 6,
  aux_sym__simple_variable_substitution_token1 = 7,
  anon_sym_DOLLAR_LBRACE = 8,
  aux_sym__braced_variable_substitution_token1 = 9,
  anon_sym_RBRACE = 10,
  anon_sym_DQUOTE = 11,
  sym__quoted_word_content = 12,
  anon_sym_LBRACE = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  sym__concat = 16,
  sym_source_file = 17,
  sym__statement = 18,
  sym_command = 19,
  sym_word_list = 20,
  sym__word = 21,
  sym_concatenation = 22,
  sym_word = 23,
  sym_variable_substitution = 24,
  sym__simple_variable_substitution = 25,
  sym__braced_variable_substitution = 26,
  sym_quoted_word = 27,
  sym_braced_word = 28,
  sym_command_substitution = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_word_list_repeat1 = 31,
  aux_sym_concatenation_repeat1 = 32,
  aux_sym_word_repeat1 = 33,
  aux_sym_quoted_word_repeat1 = 34,
  aux_sym_braced_word_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__word_content] = "_word_content",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_comment] = "comment",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_DOLLAR] = "$",
  [aux_sym__simple_variable_substitution_token1] = "_simple_variable_substitution_token1",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [aux_sym__braced_variable_substitution_token1] = "_braced_variable_substitution_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DQUOTE] = "\"",
  [sym__quoted_word_content] = "_quoted_word_content",
  [anon_sym_LBRACE] = "{",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym__concat] = "_concat",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_command] = "command",
  [sym_word_list] = "word_list",
  [sym__word] = "_word",
  [sym_concatenation] = "concatenation",
  [sym_word] = "word",
  [sym_variable_substitution] = "variable_substitution",
  [sym__simple_variable_substitution] = "_simple_variable_substitution",
  [sym__braced_variable_substitution] = "_braced_variable_substitution",
  [sym_quoted_word] = "quoted_word",
  [sym_braced_word] = "braced_word",
  [sym_command_substitution] = "command_substitution",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_word_list_repeat1] = "word_list_repeat1",
  [aux_sym_concatenation_repeat1] = "concatenation_repeat1",
  [aux_sym_word_repeat1] = "word_repeat1",
  [aux_sym_quoted_word_repeat1] = "quoted_word_repeat1",
  [aux_sym_braced_word_repeat1] = "braced_word_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__word_content] = sym__word_content,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_comment] = sym_comment,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym__simple_variable_substitution_token1] = aux_sym__simple_variable_substitution_token1,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [aux_sym__braced_variable_substitution_token1] = aux_sym__braced_variable_substitution_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__quoted_word_content] = sym__quoted_word_content,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym__concat] = sym__concat,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_command] = sym_command,
  [sym_word_list] = sym_word_list,
  [sym__word] = sym__word,
  [sym_concatenation] = sym_concatenation,
  [sym_word] = sym_word,
  [sym_variable_substitution] = sym_variable_substitution,
  [sym__simple_variable_substitution] = sym__simple_variable_substitution,
  [sym__braced_variable_substitution] = sym__braced_variable_substitution,
  [sym_quoted_word] = sym_quoted_word,
  [sym_braced_word] = sym_braced_word,
  [sym_command_substitution] = sym_command_substitution,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_word_list_repeat1] = aux_sym_word_list_repeat1,
  [aux_sym_concatenation_repeat1] = aux_sym_concatenation_repeat1,
  [aux_sym_word_repeat1] = aux_sym_word_repeat1,
  [aux_sym_quoted_word_repeat1] = aux_sym_quoted_word_repeat1,
  [aux_sym_braced_word_repeat1] = aux_sym_braced_word_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__word_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__simple_variable_substitution_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__braced_variable_substitution_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__quoted_word_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym__concat] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_word_list] = {
    .visible = true,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym_concatenation] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_variable_substitution] = {
    .visible = false,
    .named = true,
  },
  [sym__braced_variable_substitution] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_word] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_word] = {
    .visible = true,
    .named = true,
  },
  [sym_command_substitution] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_concatenation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_word_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_braced_word_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_arguments, 1},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static inline bool sym_comment_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < ' '
      ? (c < '\r'
        ? c == '\t'
        : c <= '\r')
      : (c <= ' ' || c == '"'))
    : (c <= '$' || (c < '{'
      ? (c < '['
        ? c == ';'
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static inline bool sym__word_content_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '"'
        ? c == ' '
        : c <= '"')))
    : (c <= '$' || (c < '{'
      ? (c < '['
        ? c == ';'
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == ' ') SKIP(0)
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '$') ADVANCE(16);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '}') ADVANCE(21);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r') ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '$') ADVANCE(16);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == ' ') SKIP(2)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == ' ') SKIP(5)
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '$') ADVANCE(16);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == ' ') SKIP(6)
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '$') ADVANCE(16);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r') ADVANCE(14);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment);
      if (sym_comment_character_set_1(lookahead)) ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__word_content);
      if (sym_comment_character_set_1(lookahead)) ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__word_content);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      if (!sym__word_content_character_set_1(lookahead)) ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__word_content);
      if (!sym__word_content_character_set_1(lookahead)) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__simple_variable_substitution_token1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym__braced_variable_substitution_token1);
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__braced_variable_substitution_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__quoted_word_content);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__quoted_word_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5, .external_lex_state = 2},
  [3] = {.lex_state = 5, .external_lex_state = 2},
  [4] = {.lex_state = 5, .external_lex_state = 2},
  [5] = {.lex_state = 5, .external_lex_state = 2},
  [6] = {.lex_state = 5, .external_lex_state = 2},
  [7] = {.lex_state = 5, .external_lex_state = 2},
  [8] = {.lex_state = 5, .external_lex_state = 2},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5, .external_lex_state = 2},
  [11] = {.lex_state = 5, .external_lex_state = 2},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6, .external_lex_state = 2},
  [15] = {.lex_state = 6, .external_lex_state = 2},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6, .external_lex_state = 2},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6, .external_lex_state = 3},
  [20] = {.lex_state = 6, .external_lex_state = 3},
  [21] = {.lex_state = 6, .external_lex_state = 3},
  [22] = {.lex_state = 6, .external_lex_state = 3},
  [23] = {.lex_state = 6, .external_lex_state = 3},
  [24] = {.lex_state = 6, .external_lex_state = 3},
  [25] = {.lex_state = 6, .external_lex_state = 3},
  [26] = {.lex_state = 6, .external_lex_state = 4},
  [27] = {.lex_state = 6, .external_lex_state = 4},
  [28] = {.lex_state = 6, .external_lex_state = 4},
  [29] = {.lex_state = 6, .external_lex_state = 5},
  [30] = {.lex_state = 6, .external_lex_state = 4},
  [31] = {.lex_state = 6, .external_lex_state = 5},
  [32] = {.lex_state = 6, .external_lex_state = 4},
  [33] = {.lex_state = 6, .external_lex_state = 5},
  [34] = {.lex_state = 6, .external_lex_state = 5},
  [35] = {.lex_state = 6, .external_lex_state = 5},
  [36] = {.lex_state = 6, .external_lex_state = 5},
  [37] = {.lex_state = 6, .external_lex_state = 4},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 6, .external_lex_state = 6},
  [40] = {.lex_state = 6, .external_lex_state = 5},
  [41] = {.lex_state = 6, .external_lex_state = 4},
  [42] = {.lex_state = 6, .external_lex_state = 4},
  [43] = {.lex_state = 6, .external_lex_state = 5},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 6, .external_lex_state = 6},
  [46] = {.lex_state = 6, .external_lex_state = 6},
  [47] = {.lex_state = 6, .external_lex_state = 6},
  [48] = {.lex_state = 6, .external_lex_state = 5},
  [49] = {.lex_state = 6, .external_lex_state = 5},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 6, .external_lex_state = 5},
  [52] = {.lex_state = 6, .external_lex_state = 4},
  [53] = {.lex_state = 5, .external_lex_state = 2},
  [54] = {.lex_state = 6, .external_lex_state = 4},
  [55] = {.lex_state = 6, .external_lex_state = 4},
  [56] = {.lex_state = 6, .external_lex_state = 6},
  [57] = {.lex_state = 6, .external_lex_state = 6},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 6, .external_lex_state = 2},
  [61] = {.lex_state = 6, .external_lex_state = 2},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 6, .external_lex_state = 6},
  [67] = {.lex_state = 6, .external_lex_state = 6},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 6, .external_lex_state = 6},
  [71] = {.lex_state = 6, .external_lex_state = 2},
  [72] = {.lex_state = 6, .external_lex_state = 6},
  [73] = {.lex_state = 6, .external_lex_state = 2},
  [74] = {.lex_state = 6, .external_lex_state = 6},
  [75] = {.lex_state = 6, .external_lex_state = 2},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 6, .external_lex_state = 2},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 6, .external_lex_state = 3},
  [81] = {.lex_state = 6, .external_lex_state = 3},
  [82] = {.lex_state = 6, .external_lex_state = 3},
  [83] = {.lex_state = 6, .external_lex_state = 3},
  [84] = {.lex_state = 6, .external_lex_state = 3},
  [85] = {.lex_state = 6, .external_lex_state = 3},
  [86] = {.lex_state = 6},
  [87] = {.lex_state = 6},
  [88] = {.lex_state = 6},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 0, .external_lex_state = 2},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0, .external_lex_state = 2},
  [99] = {.lex_state = 0, .external_lex_state = 2},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0, .external_lex_state = 2},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 2},
  [104] = {.lex_state = 0, .external_lex_state = 2},
  [105] = {.lex_state = 0, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 2},
  [107] = {.lex_state = 6},
  [108] = {.lex_state = 6},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 6},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0, .external_lex_state = 3},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 0, .external_lex_state = 3},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 2},
  [118] = {.lex_state = 0, .external_lex_state = 3},
  [119] = {.lex_state = 2},
  [120] = {.lex_state = 3},
  [121] = {.lex_state = 0, .external_lex_state = 3},
  [122] = {.lex_state = 3},
  [123] = {.lex_state = 3},
  [124] = {.lex_state = 3},
};

enum {
  ts_external_token__concat = 0,
  ts_external_token_RBRACE = 1,
  ts_external_token_RBRACK = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__concat] = sym__concat,
  [ts_external_token_RBRACE] = anon_sym_RBRACE,
  [ts_external_token_RBRACK] = anon_sym_RBRACK,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__concat] = true,
    [ts_external_token_RBRACE] = true,
    [ts_external_token_RBRACK] = true,
  },
  [2] = {
    [ts_external_token_RBRACK] = true,
  },
  [3] = {
    [ts_external_token_RBRACE] = true,
  },
  [4] = {
    [ts_external_token__concat] = true,
  },
  [5] = {
    [ts_external_token__concat] = true,
    [ts_external_token_RBRACK] = true,
  },
  [6] = {
    [ts_external_token__concat] = true,
    [ts_external_token_RBRACE] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__word_content] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [aux_sym__simple_variable_substitution_token1] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym__concat] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(115),
    [sym__statement] = STATE(96),
    [sym_command] = STATE(96),
    [sym__word] = STATE(13),
    [sym_concatenation] = STATE(13),
    [sym_word] = STATE(28),
    [sym_variable_substitution] = STATE(28),
    [sym__simple_variable_substitution] = STATE(55),
    [sym__braced_variable_substitution] = STATE(55),
    [sym_quoted_word] = STATE(13),
    [sym_braced_word] = STATE(13),
    [sym_command_substitution] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__word_content] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym_escape_sequence] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
  },
  [2] = {
    [sym__statement] = STATE(98),
    [sym_command] = STATE(98),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym__word_content] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [sym_comment] = ACTIONS(27),
    [sym_escape_sequence] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(41),
  },
  [3] = {
    [sym__statement] = STATE(99),
    [sym_command] = STATE(99),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym__word_content] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [sym_comment] = ACTIONS(43),
    [sym_escape_sequence] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(45),
  },
  [4] = {
    [sym__statement] = STATE(104),
    [sym_command] = STATE(104),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym__word_content] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(47),
    [anon_sym_SEMI] = ACTIONS(47),
    [sym_comment] = ACTIONS(49),
    [sym_escape_sequence] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(51),
  },
  [5] = {
    [sym__statement] = STATE(105),
    [sym_command] = STATE(105),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym__word_content] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [sym_comment] = ACTIONS(53),
    [sym_escape_sequence] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(55),
  },
  [6] = {
    [sym__statement] = STATE(101),
    [sym_command] = STATE(101),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym__word_content] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(57),
    [anon_sym_SEMI] = ACTIONS(57),
    [sym_comment] = ACTIONS(59),
    [sym_escape_sequence] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(61),
  },
  [7] = {
    [sym__statement] = STATE(102),
    [sym_command] = STATE(102),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(11),
    [sym__word_content] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(63),
    [anon_sym_SEMI] = ACTIONS(63),
    [sym_comment] = ACTIONS(65),
    [sym_escape_sequence] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(67),
  },
  [8] = {
    [sym__statement] = STATE(109),
    [sym_command] = STATE(109),
    [sym__word] = STATE(13),
    [sym_concatenation] = STATE(13),
    [sym_word] = STATE(28),
    [sym_variable_substitution] = STATE(28),
    [sym__simple_variable_substitution] = STATE(55),
    [sym__braced_variable_substitution] = STATE(55),
    [sym_quoted_word] = STATE(13),
    [sym_braced_word] = STATE(13),
    [sym_command_substitution] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym__word_content] = ACTIONS(69),
    [anon_sym_LF] = ACTIONS(72),
    [anon_sym_SEMI] = ACTIONS(72),
    [sym_comment] = ACTIONS(75),
    [sym_escape_sequence] = ACTIONS(78),
    [anon_sym_DOLLAR] = ACTIONS(81),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(84),
    [anon_sym_DQUOTE] = ACTIONS(87),
    [anon_sym_LBRACE] = ACTIONS(90),
    [anon_sym_LBRACK] = ACTIONS(93),
    [anon_sym_RBRACK] = ACTIONS(96),
  },
  [9] = {
    [sym__statement] = STATE(97),
    [sym_command] = STATE(97),
    [sym__word] = STATE(13),
    [sym_concatenation] = STATE(13),
    [sym_word] = STATE(28),
    [sym_variable_substitution] = STATE(28),
    [sym__simple_variable_substitution] = STATE(55),
    [sym__braced_variable_substitution] = STATE(55),
    [sym_quoted_word] = STATE(13),
    [sym_braced_word] = STATE(13),
    [sym_command_substitution] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(98),
    [sym__word_content] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(100),
    [anon_sym_SEMI] = ACTIONS(100),
    [sym_comment] = ACTIONS(102),
    [sym_escape_sequence] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
  },
  [10] = {
    [sym__statement] = STATE(106),
    [sym_command] = STATE(106),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym__word_content] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(104),
    [anon_sym_SEMI] = ACTIONS(104),
    [sym_comment] = ACTIONS(106),
    [sym_escape_sequence] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(108),
  },
  [11] = {
    [sym__statement] = STATE(95),
    [sym_command] = STATE(95),
    [sym__word] = STATE(14),
    [sym_concatenation] = STATE(14),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(14),
    [sym_braced_word] = STATE(14),
    [sym_command_substitution] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym__word_content] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [sym_comment] = ACTIONS(110),
    [sym_escape_sequence] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(112),
  },
  [12] = {
    [sym__statement] = STATE(111),
    [sym_command] = STATE(111),
    [sym__word] = STATE(13),
    [sym_concatenation] = STATE(13),
    [sym_word] = STATE(28),
    [sym_variable_substitution] = STATE(28),
    [sym__simple_variable_substitution] = STATE(55),
    [sym__braced_variable_substitution] = STATE(55),
    [sym_quoted_word] = STATE(13),
    [sym_braced_word] = STATE(13),
    [sym_command_substitution] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(96),
    [sym__word_content] = ACTIONS(69),
    [anon_sym_LF] = ACTIONS(114),
    [anon_sym_SEMI] = ACTIONS(114),
    [sym_comment] = ACTIONS(117),
    [sym_escape_sequence] = ACTIONS(78),
    [anon_sym_DOLLAR] = ACTIONS(81),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(84),
    [anon_sym_DQUOTE] = ACTIONS(87),
    [anon_sym_LBRACE] = ACTIONS(90),
    [anon_sym_LBRACK] = ACTIONS(93),
  },
  [13] = {
    [sym_word_list] = STATE(100),
    [sym__word] = STATE(16),
    [sym_concatenation] = STATE(16),
    [sym_word] = STATE(28),
    [sym_variable_substitution] = STATE(28),
    [sym__simple_variable_substitution] = STATE(55),
    [sym__braced_variable_substitution] = STATE(55),
    [sym_quoted_word] = STATE(16),
    [sym_braced_word] = STATE(16),
    [sym_command_substitution] = STATE(16),
    [aux_sym_word_list_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(120),
    [sym__word_content] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(120),
    [anon_sym_SEMI] = ACTIONS(120),
    [sym_escape_sequence] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
  },
  [14] = {
    [sym_word_list] = STATE(103),
    [sym__word] = STATE(17),
    [sym_concatenation] = STATE(17),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(17),
    [sym_braced_word] = STATE(17),
    [sym_command_substitution] = STATE(17),
    [aux_sym_word_list_repeat1] = STATE(17),
    [sym__word_content] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(120),
    [anon_sym_SEMI] = ACTIONS(120),
    [sym_escape_sequence] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(120),
  },
  [15] = {
    [sym__word] = STATE(15),
    [sym_concatenation] = STATE(15),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(15),
    [sym_braced_word] = STATE(15),
    [sym_command_substitution] = STATE(15),
    [aux_sym_word_list_repeat1] = STATE(15),
    [sym__word_content] = ACTIONS(122),
    [anon_sym_LF] = ACTIONS(125),
    [anon_sym_SEMI] = ACTIONS(125),
    [sym_escape_sequence] = ACTIONS(122),
    [anon_sym_DOLLAR] = ACTIONS(127),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(130),
    [anon_sym_DQUOTE] = ACTIONS(133),
    [anon_sym_LBRACE] = ACTIONS(136),
    [anon_sym_LBRACK] = ACTIONS(139),
    [anon_sym_RBRACK] = ACTIONS(125),
  },
  [16] = {
    [sym__word] = STATE(18),
    [sym_concatenation] = STATE(18),
    [sym_word] = STATE(28),
    [sym_variable_substitution] = STATE(28),
    [sym__simple_variable_substitution] = STATE(55),
    [sym__braced_variable_substitution] = STATE(55),
    [sym_quoted_word] = STATE(18),
    [sym_braced_word] = STATE(18),
    [sym_command_substitution] = STATE(18),
    [aux_sym_word_list_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(142),
    [sym__word_content] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(142),
    [anon_sym_SEMI] = ACTIONS(142),
    [sym_escape_sequence] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
  },
  [17] = {
    [sym__word] = STATE(15),
    [sym_concatenation] = STATE(15),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(40),
    [sym__braced_variable_substitution] = STATE(40),
    [sym_quoted_word] = STATE(15),
    [sym_braced_word] = STATE(15),
    [sym_command_substitution] = STATE(15),
    [aux_sym_word_list_repeat1] = STATE(15),
    [sym__word_content] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(142),
    [anon_sym_SEMI] = ACTIONS(142),
    [sym_escape_sequence] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(142),
  },
  [18] = {
    [sym__word] = STATE(18),
    [sym_concatenation] = STATE(18),
    [sym_word] = STATE(28),
    [sym_variable_substitution] = STATE(28),
    [sym__simple_variable_substitution] = STATE(55),
    [sym__braced_variable_substitution] = STATE(55),
    [sym_quoted_word] = STATE(18),
    [sym_braced_word] = STATE(18),
    [sym_command_substitution] = STATE(18),
    [aux_sym_word_list_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(125),
    [sym__word_content] = ACTIONS(144),
    [anon_sym_LF] = ACTIONS(125),
    [anon_sym_SEMI] = ACTIONS(125),
    [sym_escape_sequence] = ACTIONS(144),
    [anon_sym_DOLLAR] = ACTIONS(147),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(150),
    [anon_sym_DQUOTE] = ACTIONS(153),
    [anon_sym_LBRACE] = ACTIONS(156),
    [anon_sym_LBRACK] = ACTIONS(159),
  },
  [19] = {
    [sym__word] = STATE(20),
    [sym_concatenation] = STATE(20),
    [sym_word] = STATE(47),
    [sym_variable_substitution] = STATE(47),
    [sym__simple_variable_substitution] = STATE(72),
    [sym__braced_variable_substitution] = STATE(72),
    [sym_quoted_word] = STATE(20),
    [sym_braced_word] = STATE(20),
    [sym_command_substitution] = STATE(20),
    [aux_sym_braced_word_repeat1] = STATE(20),
    [sym__word_content] = ACTIONS(162),
    [anon_sym_LF] = ACTIONS(164),
    [sym_escape_sequence] = ACTIONS(162),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(170),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [20] = {
    [sym__word] = STATE(25),
    [sym_concatenation] = STATE(25),
    [sym_word] = STATE(47),
    [sym_variable_substitution] = STATE(47),
    [sym__simple_variable_substitution] = STATE(72),
    [sym__braced_variable_substitution] = STATE(72),
    [sym_quoted_word] = STATE(25),
    [sym_braced_word] = STATE(25),
    [sym_command_substitution] = STATE(25),
    [aux_sym_braced_word_repeat1] = STATE(25),
    [sym__word_content] = ACTIONS(162),
    [anon_sym_LF] = ACTIONS(178),
    [sym_escape_sequence] = ACTIONS(162),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(180),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [21] = {
    [sym__word] = STATE(25),
    [sym_concatenation] = STATE(25),
    [sym_word] = STATE(47),
    [sym_variable_substitution] = STATE(47),
    [sym__simple_variable_substitution] = STATE(72),
    [sym__braced_variable_substitution] = STATE(72),
    [sym_quoted_word] = STATE(25),
    [sym_braced_word] = STATE(25),
    [sym_command_substitution] = STATE(25),
    [aux_sym_braced_word_repeat1] = STATE(25),
    [sym__word_content] = ACTIONS(162),
    [anon_sym_LF] = ACTIONS(178),
    [sym_escape_sequence] = ACTIONS(162),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(182),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [22] = {
    [sym__word] = STATE(21),
    [sym_concatenation] = STATE(21),
    [sym_word] = STATE(47),
    [sym_variable_substitution] = STATE(47),
    [sym__simple_variable_substitution] = STATE(72),
    [sym__braced_variable_substitution] = STATE(72),
    [sym_quoted_word] = STATE(21),
    [sym_braced_word] = STATE(21),
    [sym_command_substitution] = STATE(21),
    [aux_sym_braced_word_repeat1] = STATE(21),
    [sym__word_content] = ACTIONS(162),
    [anon_sym_LF] = ACTIONS(184),
    [sym_escape_sequence] = ACTIONS(162),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(186),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [23] = {
    [sym__word] = STATE(24),
    [sym_concatenation] = STATE(24),
    [sym_word] = STATE(47),
    [sym_variable_substitution] = STATE(47),
    [sym__simple_variable_substitution] = STATE(72),
    [sym__braced_variable_substitution] = STATE(72),
    [sym_quoted_word] = STATE(24),
    [sym_braced_word] = STATE(24),
    [sym_command_substitution] = STATE(24),
    [aux_sym_braced_word_repeat1] = STATE(24),
    [sym__word_content] = ACTIONS(162),
    [anon_sym_LF] = ACTIONS(188),
    [sym_escape_sequence] = ACTIONS(162),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(190),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [24] = {
    [sym__word] = STATE(25),
    [sym_concatenation] = STATE(25),
    [sym_word] = STATE(47),
    [sym_variable_substitution] = STATE(47),
    [sym__simple_variable_substitution] = STATE(72),
    [sym__braced_variable_substitution] = STATE(72),
    [sym_quoted_word] = STATE(25),
    [sym_braced_word] = STATE(25),
    [sym_command_substitution] = STATE(25),
    [aux_sym_braced_word_repeat1] = STATE(25),
    [sym__word_content] = ACTIONS(162),
    [anon_sym_LF] = ACTIONS(178),
    [sym_escape_sequence] = ACTIONS(162),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(192),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [25] = {
    [sym__word] = STATE(25),
    [sym_concatenation] = STATE(25),
    [sym_word] = STATE(47),
    [sym_variable_substitution] = STATE(47),
    [sym__simple_variable_substitution] = STATE(72),
    [sym__braced_variable_substitution] = STATE(72),
    [sym_quoted_word] = STATE(25),
    [sym_braced_word] = STATE(25),
    [sym_command_substitution] = STATE(25),
    [aux_sym_braced_word_repeat1] = STATE(25),
    [sym__word_content] = ACTIONS(194),
    [anon_sym_LF] = ACTIONS(197),
    [sym_escape_sequence] = ACTIONS(194),
    [anon_sym_DOLLAR] = ACTIONS(200),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(203),
    [anon_sym_RBRACE] = ACTIONS(206),
    [anon_sym_DQUOTE] = ACTIONS(208),
    [anon_sym_LBRACE] = ACTIONS(211),
    [anon_sym_LBRACK] = ACTIONS(214),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(219), 1,
      anon_sym_DOLLAR,
    ACTIONS(221), 1,
      sym__concat,
    STATE(32), 1,
      aux_sym_word_repeat1,
    ACTIONS(217), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [21] = 4,
    ACTIONS(226), 1,
      anon_sym_DOLLAR,
    ACTIONS(228), 1,
      sym__concat,
    STATE(27), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(224), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [42] = 4,
    ACTIONS(233), 1,
      anon_sym_DOLLAR,
    ACTIONS(235), 1,
      sym__concat,
    STATE(30), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(231), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [63] = 4,
    ACTIONS(239), 1,
      anon_sym_DOLLAR,
    ACTIONS(241), 1,
      sym__concat,
    STATE(33), 1,
      aux_sym_word_repeat1,
    ACTIONS(237), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [84] = 4,
    ACTIONS(235), 1,
      sym__concat,
    ACTIONS(246), 1,
      anon_sym_DOLLAR,
    STATE(27), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(244), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [105] = 4,
    ACTIONS(233), 1,
      anon_sym_DOLLAR,
    ACTIONS(248), 1,
      sym__concat,
    STATE(34), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(231), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [126] = 4,
    ACTIONS(252), 1,
      anon_sym_DOLLAR,
    ACTIONS(254), 1,
      sym__concat,
    STATE(32), 1,
      aux_sym_word_repeat1,
    ACTIONS(250), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [147] = 4,
    ACTIONS(219), 1,
      anon_sym_DOLLAR,
    ACTIONS(257), 1,
      sym__concat,
    STATE(35), 1,
      aux_sym_word_repeat1,
    ACTIONS(217), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [168] = 4,
    ACTIONS(246), 1,
      anon_sym_DOLLAR,
    ACTIONS(248), 1,
      sym__concat,
    STATE(36), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(244), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [189] = 4,
    ACTIONS(252), 1,
      anon_sym_DOLLAR,
    ACTIONS(260), 1,
      sym__concat,
    STATE(35), 1,
      aux_sym_word_repeat1,
    ACTIONS(250), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [210] = 4,
    ACTIONS(226), 1,
      anon_sym_DOLLAR,
    ACTIONS(263), 1,
      sym__concat,
    STATE(36), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(224), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [231] = 4,
    ACTIONS(239), 1,
      anon_sym_DOLLAR,
    ACTIONS(266), 1,
      sym__concat,
    STATE(26), 1,
      aux_sym_word_repeat1,
    ACTIONS(237), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [252] = 8,
    ACTIONS(269), 1,
      sym_escape_sequence,
    ACTIONS(272), 1,
      anon_sym_DOLLAR,
    ACTIONS(275), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(278), 1,
      anon_sym_DQUOTE,
    ACTIONS(280), 1,
      sym__quoted_word_content,
    ACTIONS(283), 1,
      anon_sym_LBRACK,
    STATE(93), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(38), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [280] = 4,
    ACTIONS(219), 1,
      anon_sym_DOLLAR,
    ACTIONS(286), 1,
      sym__concat,
    STATE(46), 1,
      aux_sym_word_repeat1,
    ACTIONS(217), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [300] = 2,
    ACTIONS(291), 1,
      anon_sym_DOLLAR,
    ACTIONS(289), 10,
      sym__concat,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [316] = 2,
    ACTIONS(295), 1,
      anon_sym_DOLLAR,
    ACTIONS(293), 10,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [332] = 2,
    ACTIONS(226), 1,
      anon_sym_DOLLAR,
    ACTIONS(224), 10,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [348] = 2,
    ACTIONS(226), 1,
      anon_sym_DOLLAR,
    ACTIONS(224), 10,
      sym__concat,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [364] = 8,
    ACTIONS(297), 1,
      sym_escape_sequence,
    ACTIONS(299), 1,
      anon_sym_DOLLAR,
    ACTIONS(301), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(303), 1,
      anon_sym_DQUOTE,
    ACTIONS(305), 1,
      sym__quoted_word_content,
    ACTIONS(307), 1,
      anon_sym_LBRACK,
    STATE(93), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(38), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [392] = 4,
    ACTIONS(239), 1,
      anon_sym_DOLLAR,
    ACTIONS(309), 1,
      sym__concat,
    STATE(39), 1,
      aux_sym_word_repeat1,
    ACTIONS(237), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [412] = 4,
    ACTIONS(252), 1,
      anon_sym_DOLLAR,
    ACTIONS(312), 1,
      sym__concat,
    STATE(46), 1,
      aux_sym_word_repeat1,
    ACTIONS(250), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [432] = 4,
    ACTIONS(233), 1,
      anon_sym_DOLLAR,
    ACTIONS(315), 1,
      sym__concat,
    STATE(57), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(231), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [452] = 2,
    ACTIONS(319), 1,
      anon_sym_DOLLAR,
    ACTIONS(317), 10,
      sym__concat,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [468] = 2,
    ACTIONS(295), 1,
      anon_sym_DOLLAR,
    ACTIONS(293), 10,
      sym__concat,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [484] = 8,
    ACTIONS(297), 1,
      sym_escape_sequence,
    ACTIONS(299), 1,
      anon_sym_DOLLAR,
    ACTIONS(301), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(305), 1,
      sym__quoted_word_content,
    ACTIONS(307), 1,
      anon_sym_LBRACK,
    ACTIONS(321), 1,
      anon_sym_DQUOTE,
    STATE(93), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(38), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [512] = 2,
    ACTIONS(325), 1,
      anon_sym_DOLLAR,
    ACTIONS(323), 10,
      sym__concat,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [528] = 2,
    ACTIONS(325), 1,
      anon_sym_DOLLAR,
    ACTIONS(323), 10,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [544] = 2,
    ACTIONS(327), 2,
      sym__word_content,
      anon_sym_DOLLAR,
    ACTIONS(96), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym_comment,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [560] = 2,
    ACTIONS(319), 1,
      anon_sym_DOLLAR,
    ACTIONS(317), 10,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [576] = 2,
    ACTIONS(291), 1,
      anon_sym_DOLLAR,
    ACTIONS(289), 10,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [592] = 4,
    ACTIONS(226), 1,
      anon_sym_DOLLAR,
    ACTIONS(329), 1,
      sym__concat,
    STATE(56), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(224), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [612] = 4,
    ACTIONS(246), 1,
      anon_sym_DOLLAR,
    ACTIONS(315), 1,
      sym__concat,
    STATE(56), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(244), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [632] = 2,
    ACTIONS(327), 2,
      sym__word_content,
      anon_sym_DOLLAR,
    ACTIONS(96), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym_comment,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [648] = 8,
    ACTIONS(297), 1,
      sym_escape_sequence,
    ACTIONS(299), 1,
      anon_sym_DOLLAR,
    ACTIONS(301), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(305), 1,
      sym__quoted_word_content,
    ACTIONS(307), 1,
      anon_sym_LBRACK,
    ACTIONS(332), 1,
      anon_sym_DQUOTE,
    STATE(93), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(38), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [676] = 2,
    ACTIONS(336), 1,
      anon_sym_DOLLAR,
    ACTIONS(334), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [691] = 2,
    ACTIONS(340), 1,
      anon_sym_DOLLAR,
    ACTIONS(338), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [706] = 7,
    ACTIONS(299), 1,
      anon_sym_DOLLAR,
    ACTIONS(301), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(307), 1,
      anon_sym_LBRACK,
    ACTIONS(342), 1,
      sym_escape_sequence,
    ACTIONS(344), 1,
      sym__quoted_word_content,
    STATE(93), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(59), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [731] = 7,
    ACTIONS(299), 1,
      anon_sym_DOLLAR,
    ACTIONS(301), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(307), 1,
      anon_sym_LBRACK,
    ACTIONS(346), 1,
      sym_escape_sequence,
    ACTIONS(348), 1,
      sym__quoted_word_content,
    STATE(93), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(44), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [756] = 7,
    ACTIONS(299), 1,
      anon_sym_DOLLAR,
    ACTIONS(301), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(307), 1,
      anon_sym_LBRACK,
    ACTIONS(350), 1,
      sym_escape_sequence,
    ACTIONS(352), 1,
      sym__quoted_word_content,
    STATE(93), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(50), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [781] = 2,
    ACTIONS(356), 1,
      anon_sym_DOLLAR,
    ACTIONS(354), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [796] = 2,
    ACTIONS(226), 1,
      anon_sym_DOLLAR,
    ACTIONS(224), 9,
      sym__concat,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [811] = 2,
    ACTIONS(319), 1,
      anon_sym_DOLLAR,
    ACTIONS(317), 9,
      sym__concat,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [826] = 2,
    ACTIONS(360), 1,
      anon_sym_DOLLAR,
    ACTIONS(358), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [841] = 2,
    ACTIONS(364), 1,
      anon_sym_DOLLAR,
    ACTIONS(362), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [856] = 2,
    ACTIONS(325), 1,
      anon_sym_DOLLAR,
    ACTIONS(323), 9,
      sym__concat,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [871] = 2,
    ACTIONS(364), 1,
      anon_sym_DOLLAR,
    ACTIONS(362), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [886] = 2,
    ACTIONS(291), 1,
      anon_sym_DOLLAR,
    ACTIONS(289), 9,
      sym__concat,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [901] = 2,
    ACTIONS(368), 1,
      anon_sym_DOLLAR,
    ACTIONS(366), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [916] = 2,
    ACTIONS(295), 1,
      anon_sym_DOLLAR,
    ACTIONS(293), 9,
      sym__concat,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [931] = 2,
    ACTIONS(356), 1,
      anon_sym_DOLLAR,
    ACTIONS(354), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [946] = 2,
    ACTIONS(340), 1,
      anon_sym_DOLLAR,
    ACTIONS(338), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [961] = 2,
    ACTIONS(336), 1,
      anon_sym_DOLLAR,
    ACTIONS(334), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [976] = 2,
    ACTIONS(360), 1,
      anon_sym_DOLLAR,
    ACTIONS(358), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [991] = 2,
    ACTIONS(368), 1,
      anon_sym_DOLLAR,
    ACTIONS(366), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1006] = 2,
    ACTIONS(356), 1,
      anon_sym_DOLLAR,
    ACTIONS(354), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1020] = 2,
    ACTIONS(368), 1,
      anon_sym_DOLLAR,
    ACTIONS(366), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1034] = 2,
    ACTIONS(360), 1,
      anon_sym_DOLLAR,
    ACTIONS(358), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1048] = 2,
    ACTIONS(340), 1,
      anon_sym_DOLLAR,
    ACTIONS(338), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1062] = 2,
    ACTIONS(336), 1,
      anon_sym_DOLLAR,
    ACTIONS(334), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1076] = 2,
    ACTIONS(364), 1,
      anon_sym_DOLLAR,
    ACTIONS(362), 8,
      anon_sym_LF,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1090] = 5,
    ACTIONS(31), 1,
      anon_sym_DOLLAR,
    ACTIONS(33), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(29), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(40), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(43), 2,
      sym_word,
      sym_variable_substitution,
  [1109] = 5,
    ACTIONS(166), 1,
      anon_sym_DOLLAR,
    ACTIONS(168), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(162), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(66), 2,
      sym_word,
      sym_variable_substitution,
    STATE(72), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
  [1128] = 5,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(11), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(42), 2,
      sym_word,
      sym_variable_substitution,
    STATE(55), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
  [1147] = 2,
    ACTIONS(334), 1,
      sym__quoted_word_content,
    ACTIONS(336), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1158] = 2,
    ACTIONS(358), 1,
      sym__quoted_word_content,
    ACTIONS(360), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1169] = 2,
    ACTIONS(323), 1,
      sym__quoted_word_content,
    ACTIONS(325), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1180] = 2,
    ACTIONS(293), 1,
      sym__quoted_word_content,
    ACTIONS(295), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1191] = 2,
    ACTIONS(289), 1,
      sym__quoted_word_content,
    ACTIONS(291), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1202] = 2,
    ACTIONS(338), 1,
      sym__quoted_word_content,
    ACTIONS(340), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1213] = 2,
    ACTIONS(372), 1,
      anon_sym_RBRACK,
    ACTIONS(370), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1221] = 2,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(374), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1229] = 2,
    ACTIONS(376), 1,
      ts_builtin_sym_end,
    ACTIONS(374), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1237] = 2,
    ACTIONS(378), 1,
      anon_sym_RBRACK,
    ACTIONS(370), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1245] = 2,
    ACTIONS(380), 1,
      anon_sym_RBRACK,
    ACTIONS(370), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1253] = 1,
    ACTIONS(382), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
  [1259] = 2,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    ACTIONS(370), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1267] = 2,
    ACTIONS(112), 1,
      anon_sym_RBRACK,
    ACTIONS(370), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1275] = 1,
    ACTIONS(382), 3,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1281] = 2,
    ACTIONS(45), 1,
      anon_sym_RBRACK,
    ACTIONS(370), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1289] = 2,
    ACTIONS(384), 1,
      anon_sym_RBRACK,
    ACTIONS(370), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1297] = 2,
    ACTIONS(55), 1,
      anon_sym_RBRACK,
    ACTIONS(370), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1305] = 1,
    ACTIONS(386), 2,
      sym__word_content,
      sym_escape_sequence,
  [1310] = 1,
    ACTIONS(388), 2,
      sym__word_content,
      sym_escape_sequence,
  [1315] = 1,
    ACTIONS(370), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1320] = 1,
    ACTIONS(390), 2,
      sym__word_content,
      sym_escape_sequence,
  [1325] = 1,
    ACTIONS(374), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [1330] = 1,
    ACTIONS(392), 1,
      anon_sym_RBRACE,
  [1334] = 1,
    ACTIONS(394), 1,
      aux_sym__simple_variable_substitution_token1,
  [1338] = 1,
    ACTIONS(396), 1,
      anon_sym_RBRACE,
  [1342] = 1,
    ACTIONS(398), 1,
      ts_builtin_sym_end,
  [1346] = 1,
    ACTIONS(400), 1,
      aux_sym__simple_variable_substitution_token1,
  [1350] = 1,
    ACTIONS(402), 1,
      aux_sym__simple_variable_substitution_token1,
  [1354] = 1,
    ACTIONS(404), 1,
      anon_sym_RBRACE,
  [1358] = 1,
    ACTIONS(406), 1,
      aux_sym__simple_variable_substitution_token1,
  [1362] = 1,
    ACTIONS(408), 1,
      aux_sym__braced_variable_substitution_token1,
  [1366] = 1,
    ACTIONS(410), 1,
      anon_sym_RBRACE,
  [1370] = 1,
    ACTIONS(412), 1,
      aux_sym__braced_variable_substitution_token1,
  [1374] = 1,
    ACTIONS(414), 1,
      aux_sym__braced_variable_substitution_token1,
  [1378] = 1,
    ACTIONS(416), 1,
      aux_sym__braced_variable_substitution_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(26)] = 0,
  [SMALL_STATE(27)] = 21,
  [SMALL_STATE(28)] = 42,
  [SMALL_STATE(29)] = 63,
  [SMALL_STATE(30)] = 84,
  [SMALL_STATE(31)] = 105,
  [SMALL_STATE(32)] = 126,
  [SMALL_STATE(33)] = 147,
  [SMALL_STATE(34)] = 168,
  [SMALL_STATE(35)] = 189,
  [SMALL_STATE(36)] = 210,
  [SMALL_STATE(37)] = 231,
  [SMALL_STATE(38)] = 252,
  [SMALL_STATE(39)] = 280,
  [SMALL_STATE(40)] = 300,
  [SMALL_STATE(41)] = 316,
  [SMALL_STATE(42)] = 332,
  [SMALL_STATE(43)] = 348,
  [SMALL_STATE(44)] = 364,
  [SMALL_STATE(45)] = 392,
  [SMALL_STATE(46)] = 412,
  [SMALL_STATE(47)] = 432,
  [SMALL_STATE(48)] = 452,
  [SMALL_STATE(49)] = 468,
  [SMALL_STATE(50)] = 484,
  [SMALL_STATE(51)] = 512,
  [SMALL_STATE(52)] = 528,
  [SMALL_STATE(53)] = 544,
  [SMALL_STATE(54)] = 560,
  [SMALL_STATE(55)] = 576,
  [SMALL_STATE(56)] = 592,
  [SMALL_STATE(57)] = 612,
  [SMALL_STATE(58)] = 632,
  [SMALL_STATE(59)] = 648,
  [SMALL_STATE(60)] = 676,
  [SMALL_STATE(61)] = 691,
  [SMALL_STATE(62)] = 706,
  [SMALL_STATE(63)] = 731,
  [SMALL_STATE(64)] = 756,
  [SMALL_STATE(65)] = 781,
  [SMALL_STATE(66)] = 796,
  [SMALL_STATE(67)] = 811,
  [SMALL_STATE(68)] = 826,
  [SMALL_STATE(69)] = 841,
  [SMALL_STATE(70)] = 856,
  [SMALL_STATE(71)] = 871,
  [SMALL_STATE(72)] = 886,
  [SMALL_STATE(73)] = 901,
  [SMALL_STATE(74)] = 916,
  [SMALL_STATE(75)] = 931,
  [SMALL_STATE(76)] = 946,
  [SMALL_STATE(77)] = 961,
  [SMALL_STATE(78)] = 976,
  [SMALL_STATE(79)] = 991,
  [SMALL_STATE(80)] = 1006,
  [SMALL_STATE(81)] = 1020,
  [SMALL_STATE(82)] = 1034,
  [SMALL_STATE(83)] = 1048,
  [SMALL_STATE(84)] = 1062,
  [SMALL_STATE(85)] = 1076,
  [SMALL_STATE(86)] = 1090,
  [SMALL_STATE(87)] = 1109,
  [SMALL_STATE(88)] = 1128,
  [SMALL_STATE(89)] = 1147,
  [SMALL_STATE(90)] = 1158,
  [SMALL_STATE(91)] = 1169,
  [SMALL_STATE(92)] = 1180,
  [SMALL_STATE(93)] = 1191,
  [SMALL_STATE(94)] = 1202,
  [SMALL_STATE(95)] = 1213,
  [SMALL_STATE(96)] = 1221,
  [SMALL_STATE(97)] = 1229,
  [SMALL_STATE(98)] = 1237,
  [SMALL_STATE(99)] = 1245,
  [SMALL_STATE(100)] = 1253,
  [SMALL_STATE(101)] = 1259,
  [SMALL_STATE(102)] = 1267,
  [SMALL_STATE(103)] = 1275,
  [SMALL_STATE(104)] = 1281,
  [SMALL_STATE(105)] = 1289,
  [SMALL_STATE(106)] = 1297,
  [SMALL_STATE(107)] = 1305,
  [SMALL_STATE(108)] = 1310,
  [SMALL_STATE(109)] = 1315,
  [SMALL_STATE(110)] = 1320,
  [SMALL_STATE(111)] = 1325,
  [SMALL_STATE(112)] = 1330,
  [SMALL_STATE(113)] = 1334,
  [SMALL_STATE(114)] = 1338,
  [SMALL_STATE(115)] = 1342,
  [SMALL_STATE(116)] = 1346,
  [SMALL_STATE(117)] = 1350,
  [SMALL_STATE(118)] = 1354,
  [SMALL_STATE(119)] = 1358,
  [SMALL_STATE(120)] = 1362,
  [SMALL_STATE(121)] = 1366,
  [SMALL_STATE(122)] = 1370,
  [SMALL_STATE(123)] = 1374,
  [SMALL_STATE(124)] = 1378,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(109),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(117),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(120),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(64),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(19),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(12),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(111),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, .production_id = 1),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(29),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(116),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(124),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(62),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(23),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(4),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word_list, 1),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(37),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(117),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(120),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(64),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(19),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(6),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(45),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(25),
  [200] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(119),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(123),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_braced_word_repeat1, 2),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(63),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(22),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(10),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 2),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 2),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 2), SHIFT(108),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_concatenation_repeat1, 2),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2), SHIFT_REPEAT(88),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__word, 1),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__word, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 1), SHIFT(107),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concatenation, 2),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_concatenation, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(108),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 2), SHIFT(107),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(107),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2), SHIFT_REPEAT(86),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 1), SHIFT(108),
  [269] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(38),
  [272] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(113),
  [275] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(122),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(38),
  [283] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(7),
  [286] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 2), SHIFT(110),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_substitution, 1),
  [291] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_substitution, 1),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_variable_substitution, 2),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_variable_substitution, 2),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [303] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [309] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 1), SHIFT(110),
  [312] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(110),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2, .dynamic_precedence = 1),
  [319] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2, .dynamic_precedence = 1),
  [321] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__braced_variable_substitution, 3),
  [325] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__braced_variable_substitution, 3),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [329] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2), SHIFT_REPEAT(87),
  [332] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 4),
  [336] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 4),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 3),
  [340] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 3),
  [342] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [346] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [350] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_word, 2),
  [356] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_word, 2),
  [358] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 2),
  [360] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 2),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_word, 3),
  [364] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_word, 3),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_word, 3),
  [368] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_word, 3),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [376] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [382] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, .production_id = 2),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [398] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_tcl_external_scanner_create(void);
void tree_sitter_tcl_external_scanner_destroy(void *);
bool tree_sitter_tcl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_tcl_external_scanner_serialize(void *, char *);
void tree_sitter_tcl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tcl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__word_content,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_tcl_external_scanner_create,
      tree_sitter_tcl_external_scanner_destroy,
      tree_sitter_tcl_external_scanner_scan,
      tree_sitter_tcl_external_scanner_serialize,
      tree_sitter_tcl_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
