#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 26
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum {
  anon_sym_LF = 1,
  anon_sym_SEMI = 2,
  sym_comment = 3,
  sym__word_content = 4,
  sym_escape_sequence = 5,
  anon_sym_DOLLAR = 6,
  aux_sym__simple_variable_substitution_token1 = 7,
  anon_sym_DOLLAR_LBRACE = 8,
  aux_sym__braced_variable_substitution_token1 = 9,
  anon_sym_RBRACE = 10,
  anon_sym_DQUOTE = 11,
  sym__quoted_word_content = 12,
  anon_sym_LBRACE = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  sym__concat = 16,
  sym_source_file = 17,
  sym__statement = 18,
  sym_command = 19,
  sym_word_list = 20,
  sym__word = 21,
  sym_concatenation = 22,
  sym_word = 23,
  sym_variable_substitution = 24,
  sym__simple_variable_substitution = 25,
  sym__braced_variable_substitution = 26,
  sym_quoted_word = 27,
  sym_braced_word = 28,
  sym_command_substitution = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_word_list_repeat1 = 31,
  aux_sym_concatenation_repeat1 = 32,
  aux_sym_word_repeat1 = 33,
  aux_sym_quoted_word_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_comment] = "comment",
  [sym__word_content] = "_word_content",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_DOLLAR] = "$",
  [aux_sym__simple_variable_substitution_token1] = "_simple_variable_substitution_token1",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [aux_sym__braced_variable_substitution_token1] = "_braced_variable_substitution_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DQUOTE] = "\"",
  [sym__quoted_word_content] = "_quoted_word_content",
  [anon_sym_LBRACE] = "{",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym__concat] = "_concat",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_command] = "command",
  [sym_word_list] = "word_list",
  [sym__word] = "_word",
  [sym_concatenation] = "concatenation",
  [sym_word] = "word",
  [sym_variable_substitution] = "variable_substitution",
  [sym__simple_variable_substitution] = "_simple_variable_substitution",
  [sym__braced_variable_substitution] = "_braced_variable_substitution",
  [sym_quoted_word] = "quoted_word",
  [sym_braced_word] = "braced_word",
  [sym_command_substitution] = "command_substitution",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_word_list_repeat1] = "word_list_repeat1",
  [aux_sym_concatenation_repeat1] = "concatenation_repeat1",
  [aux_sym_word_repeat1] = "word_repeat1",
  [aux_sym_quoted_word_repeat1] = "quoted_word_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_comment] = sym_comment,
  [sym__word_content] = sym__word_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym__simple_variable_substitution_token1] = aux_sym__simple_variable_substitution_token1,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [aux_sym__braced_variable_substitution_token1] = aux_sym__braced_variable_substitution_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__quoted_word_content] = sym__quoted_word_content,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym__concat] = sym__concat,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_command] = sym_command,
  [sym_word_list] = sym_word_list,
  [sym__word] = sym__word,
  [sym_concatenation] = sym_concatenation,
  [sym_word] = sym_word,
  [sym_variable_substitution] = sym_variable_substitution,
  [sym__simple_variable_substitution] = sym__simple_variable_substitution,
  [sym__braced_variable_substitution] = sym__braced_variable_substitution,
  [sym_quoted_word] = sym_quoted_word,
  [sym_braced_word] = sym_braced_word,
  [sym_command_substitution] = sym_command_substitution,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_word_list_repeat1] = aux_sym_word_list_repeat1,
  [aux_sym_concatenation_repeat1] = aux_sym_concatenation_repeat1,
  [aux_sym_word_repeat1] = aux_sym_word_repeat1,
  [aux_sym_quoted_word_repeat1] = aux_sym_quoted_word_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__word_content] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__simple_variable_substitution_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__braced_variable_substitution_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__quoted_word_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym__concat] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_word_list] = {
    .visible = true,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym_concatenation] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_variable_substitution] = {
    .visible = false,
    .named = true,
  },
  [sym__braced_variable_substitution] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_word] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_word] = {
    .visible = true,
    .named = true,
  },
  [sym_command_substitution] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_concatenation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_word_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_arguments, 1},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static inline bool sym_comment_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < ' '
      ? (c < '\r'
        ? c == '\t'
        : c <= '\r')
      : (c <= ' ' || c == '"'))
    : (c <= '$' || (c < '{'
      ? (c < '['
        ? c == ';'
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static inline bool sym__word_content_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '"'
        ? c == ' '
        : c <= '"')))
    : (c <= '$' || (c < '{'
      ? (c < '['
        ? c == ';'
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '$') ADVANCE(17);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '$') ADVANCE(17);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != ';' &&
          lookahead != ']') ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '$') ADVANCE(17);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '$') ADVANCE(17);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(15);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '$') ADVANCE(17);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (lookahead != 0 &&
          lookahead != ';' &&
          lookahead != '}') ADVANCE(15);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (sym_comment_character_set_1(lookahead)) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__word_content);
      if (sym_comment_character_set_1(lookahead)) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__word_content);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      if (!sym__word_content_character_set_1(lookahead)) ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__word_content);
      if (!sym__word_content_character_set_1(lookahead)) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '{') ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym__simple_variable_substitution_token1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__braced_variable_substitution_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__braced_variable_substitution_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__quoted_word_content);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__quoted_word_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 6, .external_lex_state = 1},
  [27] = {.lex_state = 6, .external_lex_state = 1},
  [28] = {.lex_state = 6, .external_lex_state = 1},
  [29] = {.lex_state = 6, .external_lex_state = 1},
  [30] = {.lex_state = 6, .external_lex_state = 1},
  [31] = {.lex_state = 6, .external_lex_state = 1},
  [32] = {.lex_state = 6, .external_lex_state = 1},
  [33] = {.lex_state = 6, .external_lex_state = 1},
  [34] = {.lex_state = 6, .external_lex_state = 1},
  [35] = {.lex_state = 6, .external_lex_state = 1},
  [36] = {.lex_state = 6, .external_lex_state = 1},
  [37] = {.lex_state = 6, .external_lex_state = 1},
  [38] = {.lex_state = 6, .external_lex_state = 1},
  [39] = {.lex_state = 6, .external_lex_state = 1},
  [40] = {.lex_state = 6, .external_lex_state = 1},
  [41] = {.lex_state = 6, .external_lex_state = 1},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 6, .external_lex_state = 1},
  [44] = {.lex_state = 6, .external_lex_state = 1},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 6, .external_lex_state = 1},
  [48] = {.lex_state = 6, .external_lex_state = 1},
  [49] = {.lex_state = 6, .external_lex_state = 1},
  [50] = {.lex_state = 6, .external_lex_state = 1},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 1, .external_lex_state = 1},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 1, .external_lex_state = 1},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 1, .external_lex_state = 1},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 1, .external_lex_state = 1},
  [71] = {.lex_state = 1, .external_lex_state = 1},
  [72] = {.lex_state = 1, .external_lex_state = 1},
  [73] = {.lex_state = 1, .external_lex_state = 1},
  [74] = {.lex_state = 7},
  [75] = {.lex_state = 7},
  [76] = {.lex_state = 1, .external_lex_state = 1},
  [77] = {.lex_state = 1, .external_lex_state = 1},
  [78] = {.lex_state = 1, .external_lex_state = 1},
  [79] = {.lex_state = 1, .external_lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 6},
  [96] = {.lex_state = 6},
  [97] = {.lex_state = 6},
  [98] = {.lex_state = 6},
  [99] = {.lex_state = 6},
  [100] = {.lex_state = 6},
  [101] = {.lex_state = 6},
  [102] = {.lex_state = 6},
  [103] = {.lex_state = 6},
  [104] = {.lex_state = 6},
  [105] = {.lex_state = 6},
  [106] = {.lex_state = 6},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 6},
  [110] = {.lex_state = 6},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 3},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 3},
  [117] = {.lex_state = 3},
  [118] = {.lex_state = 3},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 4},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 4},
  [123] = {.lex_state = 4},
  [124] = {.lex_state = 4},
};

enum {
  ts_external_token__concat = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__concat] = sym__concat,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__concat] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__word_content] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [aux_sym__simple_variable_substitution_token1] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym__concat] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(115),
    [sym__statement] = STATE(96),
    [sym_command] = STATE(96),
    [sym__word] = STATE(10),
    [sym_concatenation] = STATE(10),
    [sym_word] = STATE(35),
    [sym_variable_substitution] = STATE(35),
    [sym__simple_variable_substitution] = STATE(39),
    [sym__braced_variable_substitution] = STATE(39),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym__word_content] = ACTIONS(7),
    [sym_escape_sequence] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [2] = {
    [sym__statement] = STATE(102),
    [sym_command] = STATE(102),
    [sym__word] = STATE(7),
    [sym_concatenation] = STATE(7),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(7),
    [sym_braced_word] = STATE(7),
    [sym_command_substitution] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(21),
    [sym__word_content] = ACTIONS(23),
    [sym_escape_sequence] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(37),
  },
  [3] = {
    [sym__statement] = STATE(109),
    [sym_command] = STATE(109),
    [sym__word] = STATE(7),
    [sym_concatenation] = STATE(7),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(7),
    [sym_braced_word] = STATE(7),
    [sym_command_substitution] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(39),
    [sym__word_content] = ACTIONS(42),
    [sym_escape_sequence] = ACTIONS(45),
    [anon_sym_DOLLAR] = ACTIONS(48),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(54),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(60),
    [anon_sym_RBRACK] = ACTIONS(63),
  },
  [4] = {
    [sym__statement] = STATE(98),
    [sym_command] = STATE(98),
    [sym__word] = STATE(7),
    [sym_concatenation] = STATE(7),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(7),
    [sym_braced_word] = STATE(7),
    [sym_command_substitution] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(65),
    [sym__word_content] = ACTIONS(23),
    [sym_escape_sequence] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(67),
  },
  [5] = {
    [sym__statement] = STATE(99),
    [sym_command] = STATE(99),
    [sym__word] = STATE(7),
    [sym_concatenation] = STATE(7),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(7),
    [sym_braced_word] = STATE(7),
    [sym_command_substitution] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(69),
    [sym__word_content] = ACTIONS(23),
    [sym_escape_sequence] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(71),
  },
  [6] = {
    [sym__statement] = STATE(104),
    [sym_command] = STATE(104),
    [sym__word] = STATE(7),
    [sym_concatenation] = STATE(7),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(7),
    [sym_braced_word] = STATE(7),
    [sym_command_substitution] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(73),
    [sym__word_content] = ACTIONS(23),
    [sym_escape_sequence] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(75),
  },
  [7] = {
    [sym_word_list] = STATE(97),
    [sym__word] = STATE(16),
    [sym_concatenation] = STATE(16),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(16),
    [sym_braced_word] = STATE(16),
    [sym_command_substitution] = STATE(16),
    [aux_sym_word_list_repeat1] = STATE(16),
    [anon_sym_LF] = ACTIONS(77),
    [anon_sym_SEMI] = ACTIONS(79),
    [sym__word_content] = ACTIONS(23),
    [sym_escape_sequence] = ACTIONS(23),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(83),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(87),
    [anon_sym_RBRACK] = ACTIONS(79),
  },
  [8] = {
    [sym__statement] = STATE(100),
    [sym_command] = STATE(100),
    [sym__word] = STATE(7),
    [sym_concatenation] = STATE(7),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(7),
    [sym_braced_word] = STATE(7),
    [sym_command_substitution] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_comment] = ACTIONS(89),
    [sym__word_content] = ACTIONS(23),
    [sym_escape_sequence] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(91),
  },
  [9] = {
    [sym__statement] = STATE(110),
    [sym_command] = STATE(110),
    [sym__word] = STATE(7),
    [sym_concatenation] = STATE(7),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(7),
    [sym_braced_word] = STATE(7),
    [sym_command_substitution] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym_comment] = ACTIONS(93),
    [sym__word_content] = ACTIONS(42),
    [sym_escape_sequence] = ACTIONS(45),
    [anon_sym_DOLLAR] = ACTIONS(48),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(54),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(60),
  },
  [10] = {
    [sym_word_list] = STATE(106),
    [sym__word] = STATE(15),
    [sym_concatenation] = STATE(15),
    [sym_word] = STATE(35),
    [sym_variable_substitution] = STATE(35),
    [sym__simple_variable_substitution] = STATE(39),
    [sym__braced_variable_substitution] = STATE(39),
    [sym_quoted_word] = STATE(15),
    [sym_braced_word] = STATE(15),
    [sym_command_substitution] = STATE(15),
    [aux_sym_word_list_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(77),
    [anon_sym_LF] = ACTIONS(77),
    [anon_sym_SEMI] = ACTIONS(79),
    [sym__word_content] = ACTIONS(7),
    [sym_escape_sequence] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(96),
    [anon_sym_DQUOTE] = ACTIONS(98),
    [anon_sym_LBRACE] = ACTIONS(100),
    [anon_sym_LBRACK] = ACTIONS(102),
  },
  [11] = {
    [sym__statement] = STATE(103),
    [sym_command] = STATE(103),
    [sym__word] = STATE(7),
    [sym_concatenation] = STATE(7),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(7),
    [sym_braced_word] = STATE(7),
    [sym_command_substitution] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(104),
    [sym__word_content] = ACTIONS(23),
    [sym_escape_sequence] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(106),
  },
  [12] = {
    [sym__statement] = STATE(101),
    [sym_command] = STATE(101),
    [sym__word] = STATE(7),
    [sym_concatenation] = STATE(7),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(7),
    [sym_braced_word] = STATE(7),
    [sym_command_substitution] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(11),
    [sym_comment] = ACTIONS(108),
    [sym__word_content] = ACTIONS(23),
    [sym_escape_sequence] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(110),
  },
  [13] = {
    [sym__statement] = STATE(105),
    [sym_command] = STATE(105),
    [sym__word] = STATE(10),
    [sym_concatenation] = STATE(10),
    [sym_word] = STATE(35),
    [sym_variable_substitution] = STATE(35),
    [sym__simple_variable_substitution] = STATE(39),
    [sym__braced_variable_substitution] = STATE(39),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_comment] = ACTIONS(114),
    [sym__word_content] = ACTIONS(7),
    [sym_escape_sequence] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [14] = {
    [sym__statement] = STATE(95),
    [sym_command] = STATE(95),
    [sym__word] = STATE(7),
    [sym_concatenation] = STATE(7),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(7),
    [sym_braced_word] = STATE(7),
    [sym_command_substitution] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_comment] = ACTIONS(116),
    [sym__word_content] = ACTIONS(23),
    [sym_escape_sequence] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(118),
  },
  [15] = {
    [sym__word] = STATE(17),
    [sym_concatenation] = STATE(17),
    [sym_word] = STATE(35),
    [sym_variable_substitution] = STATE(35),
    [sym__simple_variable_substitution] = STATE(39),
    [sym__braced_variable_substitution] = STATE(39),
    [sym_quoted_word] = STATE(17),
    [sym_braced_word] = STATE(17),
    [sym_command_substitution] = STATE(17),
    [aux_sym_word_list_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(120),
    [anon_sym_LF] = ACTIONS(120),
    [anon_sym_SEMI] = ACTIONS(122),
    [sym__word_content] = ACTIONS(7),
    [sym_escape_sequence] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(96),
    [anon_sym_DQUOTE] = ACTIONS(98),
    [anon_sym_LBRACE] = ACTIONS(100),
    [anon_sym_LBRACK] = ACTIONS(102),
  },
  [16] = {
    [sym__word] = STATE(18),
    [sym_concatenation] = STATE(18),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(18),
    [sym_braced_word] = STATE(18),
    [sym_command_substitution] = STATE(18),
    [aux_sym_word_list_repeat1] = STATE(18),
    [anon_sym_LF] = ACTIONS(120),
    [anon_sym_SEMI] = ACTIONS(122),
    [sym__word_content] = ACTIONS(23),
    [sym_escape_sequence] = ACTIONS(23),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(83),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(87),
    [anon_sym_RBRACK] = ACTIONS(122),
  },
  [17] = {
    [sym__word] = STATE(17),
    [sym_concatenation] = STATE(17),
    [sym_word] = STATE(35),
    [sym_variable_substitution] = STATE(35),
    [sym__simple_variable_substitution] = STATE(39),
    [sym__braced_variable_substitution] = STATE(39),
    [sym_quoted_word] = STATE(17),
    [sym_braced_word] = STATE(17),
    [sym_command_substitution] = STATE(17),
    [aux_sym_word_list_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(124),
    [anon_sym_LF] = ACTIONS(124),
    [anon_sym_SEMI] = ACTIONS(126),
    [sym__word_content] = ACTIONS(128),
    [sym_escape_sequence] = ACTIONS(128),
    [anon_sym_DOLLAR] = ACTIONS(131),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(134),
    [anon_sym_DQUOTE] = ACTIONS(137),
    [anon_sym_LBRACE] = ACTIONS(140),
    [anon_sym_LBRACK] = ACTIONS(143),
  },
  [18] = {
    [sym__word] = STATE(18),
    [sym_concatenation] = STATE(18),
    [sym_word] = STATE(31),
    [sym_variable_substitution] = STATE(31),
    [sym__simple_variable_substitution] = STATE(43),
    [sym__braced_variable_substitution] = STATE(43),
    [sym_quoted_word] = STATE(18),
    [sym_braced_word] = STATE(18),
    [sym_command_substitution] = STATE(18),
    [aux_sym_word_list_repeat1] = STATE(18),
    [anon_sym_LF] = ACTIONS(124),
    [anon_sym_SEMI] = ACTIONS(126),
    [sym__word_content] = ACTIONS(146),
    [sym_escape_sequence] = ACTIONS(146),
    [anon_sym_DOLLAR] = ACTIONS(149),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(152),
    [anon_sym_DQUOTE] = ACTIONS(155),
    [anon_sym_LBRACE] = ACTIONS(158),
    [anon_sym_LBRACK] = ACTIONS(161),
    [anon_sym_RBRACK] = ACTIONS(126),
  },
  [19] = {
    [sym__word] = STATE(22),
    [sym_concatenation] = STATE(22),
    [sym_word] = STATE(70),
    [sym_variable_substitution] = STATE(70),
    [sym__simple_variable_substitution] = STATE(73),
    [sym__braced_variable_substitution] = STATE(73),
    [sym_quoted_word] = STATE(22),
    [sym_braced_word] = STATE(22),
    [sym_command_substitution] = STATE(22),
    [aux_sym_word_list_repeat1] = STATE(22),
    [sym__word_content] = ACTIONS(164),
    [sym_escape_sequence] = ACTIONS(164),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(170),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [20] = {
    [sym__word] = STATE(24),
    [sym_concatenation] = STATE(24),
    [sym_word] = STATE(70),
    [sym_variable_substitution] = STATE(70),
    [sym__simple_variable_substitution] = STATE(73),
    [sym__braced_variable_substitution] = STATE(73),
    [sym_quoted_word] = STATE(24),
    [sym_braced_word] = STATE(24),
    [sym_command_substitution] = STATE(24),
    [aux_sym_word_list_repeat1] = STATE(24),
    [sym__word_content] = ACTIONS(164),
    [sym_escape_sequence] = ACTIONS(164),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(178),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [21] = {
    [sym__word] = STATE(20),
    [sym_concatenation] = STATE(20),
    [sym_word] = STATE(70),
    [sym_variable_substitution] = STATE(70),
    [sym__simple_variable_substitution] = STATE(73),
    [sym__braced_variable_substitution] = STATE(73),
    [sym_quoted_word] = STATE(20),
    [sym_braced_word] = STATE(20),
    [sym_command_substitution] = STATE(20),
    [aux_sym_word_list_repeat1] = STATE(20),
    [sym__word_content] = ACTIONS(164),
    [sym_escape_sequence] = ACTIONS(164),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(180),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [22] = {
    [sym__word] = STATE(24),
    [sym_concatenation] = STATE(24),
    [sym_word] = STATE(70),
    [sym_variable_substitution] = STATE(70),
    [sym__simple_variable_substitution] = STATE(73),
    [sym__braced_variable_substitution] = STATE(73),
    [sym_quoted_word] = STATE(24),
    [sym_braced_word] = STATE(24),
    [sym_command_substitution] = STATE(24),
    [aux_sym_word_list_repeat1] = STATE(24),
    [sym__word_content] = ACTIONS(164),
    [sym_escape_sequence] = ACTIONS(164),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(182),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [23] = {
    [sym__word] = STATE(24),
    [sym_concatenation] = STATE(24),
    [sym_word] = STATE(70),
    [sym_variable_substitution] = STATE(70),
    [sym__simple_variable_substitution] = STATE(73),
    [sym__braced_variable_substitution] = STATE(73),
    [sym_quoted_word] = STATE(24),
    [sym_braced_word] = STATE(24),
    [sym_command_substitution] = STATE(24),
    [aux_sym_word_list_repeat1] = STATE(24),
    [sym__word_content] = ACTIONS(164),
    [sym_escape_sequence] = ACTIONS(164),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(184),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
  [24] = {
    [sym__word] = STATE(24),
    [sym_concatenation] = STATE(24),
    [sym_word] = STATE(70),
    [sym_variable_substitution] = STATE(70),
    [sym__simple_variable_substitution] = STATE(73),
    [sym__braced_variable_substitution] = STATE(73),
    [sym_quoted_word] = STATE(24),
    [sym_braced_word] = STATE(24),
    [sym_command_substitution] = STATE(24),
    [aux_sym_word_list_repeat1] = STATE(24),
    [sym__word_content] = ACTIONS(186),
    [sym_escape_sequence] = ACTIONS(186),
    [anon_sym_DOLLAR] = ACTIONS(189),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(192),
    [anon_sym_RBRACE] = ACTIONS(124),
    [anon_sym_DQUOTE] = ACTIONS(195),
    [anon_sym_LBRACE] = ACTIONS(198),
    [anon_sym_LBRACK] = ACTIONS(201),
  },
  [25] = {
    [sym__word] = STATE(23),
    [sym_concatenation] = STATE(23),
    [sym_word] = STATE(70),
    [sym_variable_substitution] = STATE(70),
    [sym__simple_variable_substitution] = STATE(73),
    [sym__braced_variable_substitution] = STATE(73),
    [sym_quoted_word] = STATE(23),
    [sym_braced_word] = STATE(23),
    [sym_command_substitution] = STATE(23),
    [aux_sym_word_list_repeat1] = STATE(23),
    [sym__word_content] = ACTIONS(164),
    [sym_escape_sequence] = ACTIONS(164),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(204),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(176),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(206), 1,
      anon_sym_LF,
    ACTIONS(210), 1,
      sym__concat,
    STATE(26), 1,
      aux_sym_word_repeat1,
    ACTIONS(208), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [21] = 4,
    ACTIONS(213), 1,
      anon_sym_LF,
    ACTIONS(217), 1,
      sym__concat,
    STATE(27), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(215), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [42] = 4,
    ACTIONS(224), 1,
      sym__concat,
    STATE(36), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(220), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(222), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [63] = 4,
    ACTIONS(230), 1,
      sym__concat,
    STATE(32), 1,
      aux_sym_word_repeat1,
    ACTIONS(226), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(228), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [84] = 4,
    ACTIONS(233), 1,
      anon_sym_LF,
    ACTIONS(237), 1,
      sym__concat,
    STATE(33), 1,
      aux_sym_word_repeat1,
    ACTIONS(235), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [105] = 4,
    ACTIONS(240), 1,
      anon_sym_LF,
    ACTIONS(244), 1,
      sym__concat,
    STATE(34), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(242), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [126] = 4,
    ACTIONS(246), 1,
      sym__concat,
    STATE(32), 1,
      aux_sym_word_repeat1,
    ACTIONS(206), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(208), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [147] = 4,
    ACTIONS(226), 1,
      anon_sym_LF,
    ACTIONS(249), 1,
      sym__concat,
    STATE(26), 1,
      aux_sym_word_repeat1,
    ACTIONS(228), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [168] = 4,
    ACTIONS(220), 1,
      anon_sym_LF,
    ACTIONS(244), 1,
      sym__concat,
    STATE(27), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(222), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [189] = 4,
    ACTIONS(224), 1,
      sym__concat,
    STATE(28), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(240), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(242), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [210] = 4,
    ACTIONS(252), 1,
      sym__concat,
    STATE(36), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(213), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(215), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [231] = 4,
    ACTIONS(255), 1,
      sym__concat,
    STATE(29), 1,
      aux_sym_word_repeat1,
    ACTIONS(233), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(235), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [252] = 2,
    ACTIONS(213), 2,
      sym__concat,
      anon_sym_LF,
    ACTIONS(215), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [268] = 2,
    ACTIONS(258), 3,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(260), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [284] = 2,
    ACTIONS(213), 3,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(215), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [300] = 2,
    ACTIONS(262), 2,
      sym__concat,
      anon_sym_LF,
    ACTIONS(264), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [316] = 8,
    ACTIONS(266), 1,
      sym_escape_sequence,
    ACTIONS(268), 1,
      anon_sym_DOLLAR,
    ACTIONS(270), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(272), 1,
      anon_sym_DQUOTE,
    ACTIONS(274), 1,
      sym__quoted_word_content,
    ACTIONS(276), 1,
      anon_sym_LBRACK,
    STATE(90), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(46), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [344] = 2,
    ACTIONS(258), 2,
      sym__concat,
      anon_sym_LF,
    ACTIONS(260), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [360] = 2,
    ACTIONS(278), 2,
      sym__concat,
      anon_sym_LF,
    ACTIONS(280), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [376] = 8,
    ACTIONS(266), 1,
      sym_escape_sequence,
    ACTIONS(268), 1,
      anon_sym_DOLLAR,
    ACTIONS(270), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(274), 1,
      sym__quoted_word_content,
    ACTIONS(276), 1,
      anon_sym_LBRACK,
    ACTIONS(282), 1,
      anon_sym_DQUOTE,
    STATE(90), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(46), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [404] = 8,
    ACTIONS(284), 1,
      sym_escape_sequence,
    ACTIONS(287), 1,
      anon_sym_DOLLAR,
    ACTIONS(290), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(293), 1,
      anon_sym_DQUOTE,
    ACTIONS(295), 1,
      sym__quoted_word_content,
    ACTIONS(298), 1,
      anon_sym_LBRACK,
    STATE(90), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(46), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [432] = 2,
    ACTIONS(301), 2,
      sym__concat,
      anon_sym_LF,
    ACTIONS(303), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [448] = 2,
    ACTIONS(262), 3,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(264), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [464] = 2,
    ACTIONS(278), 3,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(280), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [480] = 2,
    ACTIONS(301), 3,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(303), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [496] = 8,
    ACTIONS(266), 1,
      sym_escape_sequence,
    ACTIONS(268), 1,
      anon_sym_DOLLAR,
    ACTIONS(270), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(274), 1,
      sym__quoted_word_content,
    ACTIONS(276), 1,
      anon_sym_LBRACK,
    ACTIONS(305), 1,
      anon_sym_DQUOTE,
    STATE(90), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(46), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [524] = 2,
    ACTIONS(307), 1,
      anon_sym_LF,
    ACTIONS(309), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [539] = 2,
    ACTIONS(311), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(313), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [554] = 7,
    ACTIONS(268), 1,
      anon_sym_DOLLAR,
    ACTIONS(270), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(276), 1,
      anon_sym_LBRACK,
    ACTIONS(315), 1,
      sym_escape_sequence,
    ACTIONS(317), 1,
      sym__quoted_word_content,
    STATE(90), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(51), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [579] = 7,
    ACTIONS(268), 1,
      anon_sym_DOLLAR,
    ACTIONS(270), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(276), 1,
      anon_sym_LBRACK,
    ACTIONS(319), 1,
      sym_escape_sequence,
    ACTIONS(321), 1,
      sym__quoted_word_content,
    STATE(90), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(42), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [604] = 7,
    ACTIONS(268), 1,
      anon_sym_DOLLAR,
    ACTIONS(270), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(276), 1,
      anon_sym_LBRACK,
    ACTIONS(323), 1,
      sym_escape_sequence,
    ACTIONS(325), 1,
      sym__quoted_word_content,
    STATE(90), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(45), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [629] = 4,
    ACTIONS(222), 1,
      anon_sym_DOLLAR,
    ACTIONS(327), 1,
      sym__concat,
    STATE(66), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(220), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [648] = 2,
    ACTIONS(329), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(331), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [663] = 4,
    ACTIONS(208), 1,
      anon_sym_DOLLAR,
    ACTIONS(333), 1,
      sym__concat,
    STATE(59), 1,
      aux_sym_word_repeat1,
    ACTIONS(206), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [682] = 2,
    ACTIONS(336), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(338), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [697] = 2,
    ACTIONS(311), 1,
      anon_sym_LF,
    ACTIONS(313), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [712] = 2,
    ACTIONS(340), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(342), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [727] = 2,
    ACTIONS(336), 1,
      anon_sym_LF,
    ACTIONS(338), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [742] = 2,
    ACTIONS(344), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(346), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [757] = 2,
    ACTIONS(329), 1,
      anon_sym_LF,
    ACTIONS(331), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [772] = 4,
    ACTIONS(215), 1,
      anon_sym_DOLLAR,
    ACTIONS(348), 1,
      sym__concat,
    STATE(66), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(213), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [791] = 2,
    ACTIONS(340), 1,
      anon_sym_LF,
    ACTIONS(342), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [806] = 2,
    ACTIONS(344), 1,
      anon_sym_LF,
    ACTIONS(346), 9,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [821] = 2,
    ACTIONS(307), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(309), 8,
      anon_sym_SEMI,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [836] = 4,
    ACTIONS(242), 1,
      anon_sym_DOLLAR,
    ACTIONS(327), 1,
      sym__concat,
    STATE(57), 1,
      aux_sym_concatenation_repeat1,
    ACTIONS(240), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [855] = 4,
    ACTIONS(235), 1,
      anon_sym_DOLLAR,
    ACTIONS(351), 1,
      sym__concat,
    STATE(72), 1,
      aux_sym_word_repeat1,
    ACTIONS(233), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [874] = 4,
    ACTIONS(228), 1,
      anon_sym_DOLLAR,
    ACTIONS(354), 1,
      sym__concat,
    STATE(59), 1,
      aux_sym_word_repeat1,
    ACTIONS(226), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [893] = 2,
    ACTIONS(260), 1,
      anon_sym_DOLLAR,
    ACTIONS(258), 8,
      sym__concat,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [907] = 2,
    ACTIONS(357), 2,
      sym__word_content,
      anon_sym_DOLLAR,
    ACTIONS(63), 7,
      sym_comment,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [921] = 2,
    ACTIONS(357), 2,
      sym__word_content,
      anon_sym_DOLLAR,
    ACTIONS(63), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [935] = 2,
    ACTIONS(215), 1,
      anon_sym_DOLLAR,
    ACTIONS(213), 8,
      sym__concat,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [949] = 2,
    ACTIONS(280), 1,
      anon_sym_DOLLAR,
    ACTIONS(278), 8,
      sym__concat,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [963] = 2,
    ACTIONS(264), 1,
      anon_sym_DOLLAR,
    ACTIONS(262), 8,
      sym__concat,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [977] = 2,
    ACTIONS(303), 1,
      anon_sym_DOLLAR,
    ACTIONS(301), 8,
      sym__concat,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [991] = 2,
    ACTIONS(338), 1,
      anon_sym_DOLLAR,
    ACTIONS(336), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1004] = 5,
    ACTIONS(27), 1,
      anon_sym_DOLLAR,
    ACTIONS(29), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(25), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(38), 2,
      sym_word,
      sym_variable_substitution,
    STATE(43), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
  [1023] = 2,
    ACTIONS(313), 1,
      anon_sym_DOLLAR,
    ACTIONS(311), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1036] = 2,
    ACTIONS(331), 1,
      anon_sym_DOLLAR,
    ACTIONS(329), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1049] = 2,
    ACTIONS(309), 1,
      anon_sym_DOLLAR,
    ACTIONS(307), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1062] = 5,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(9), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(39), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(40), 2,
      sym_word,
      sym_variable_substitution,
  [1081] = 2,
    ACTIONS(346), 1,
      anon_sym_DOLLAR,
    ACTIONS(344), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1094] = 2,
    ACTIONS(342), 1,
      anon_sym_DOLLAR,
    ACTIONS(340), 7,
      sym__word_content,
      sym_escape_sequence,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1107] = 5,
    ACTIONS(166), 1,
      anon_sym_DOLLAR,
    ACTIONS(168), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(164), 2,
      sym__word_content,
      sym_escape_sequence,
    STATE(73), 2,
      sym__simple_variable_substitution,
      sym__braced_variable_substitution,
    STATE(76), 2,
      sym_word,
      sym_variable_substitution,
  [1126] = 2,
    ACTIONS(336), 1,
      sym__quoted_word_content,
    ACTIONS(338), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1137] = 2,
    ACTIONS(258), 1,
      sym__quoted_word_content,
    ACTIONS(260), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1148] = 2,
    ACTIONS(301), 1,
      sym__quoted_word_content,
    ACTIONS(303), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1159] = 2,
    ACTIONS(307), 1,
      sym__quoted_word_content,
    ACTIONS(309), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1170] = 2,
    ACTIONS(311), 1,
      sym__quoted_word_content,
    ACTIONS(313), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1181] = 2,
    ACTIONS(262), 1,
      sym__quoted_word_content,
    ACTIONS(264), 5,
      sym_escape_sequence,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1192] = 3,
    ACTIONS(359), 1,
      anon_sym_LF,
    ACTIONS(361), 1,
      anon_sym_SEMI,
    ACTIONS(363), 1,
      anon_sym_RBRACK,
  [1202] = 3,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(365), 1,
      anon_sym_LF,
    ACTIONS(367), 1,
      anon_sym_SEMI,
  [1212] = 2,
    ACTIONS(369), 1,
      anon_sym_LF,
    ACTIONS(371), 2,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1220] = 3,
    ACTIONS(359), 1,
      anon_sym_LF,
    ACTIONS(361), 1,
      anon_sym_SEMI,
    ACTIONS(373), 1,
      anon_sym_RBRACK,
  [1230] = 3,
    ACTIONS(359), 1,
      anon_sym_LF,
    ACTIONS(361), 1,
      anon_sym_SEMI,
    ACTIONS(375), 1,
      anon_sym_RBRACK,
  [1240] = 3,
    ACTIONS(359), 1,
      anon_sym_LF,
    ACTIONS(361), 1,
      anon_sym_SEMI,
    ACTIONS(377), 1,
      anon_sym_RBRACK,
  [1250] = 3,
    ACTIONS(359), 1,
      anon_sym_LF,
    ACTIONS(361), 1,
      anon_sym_SEMI,
    ACTIONS(379), 1,
      anon_sym_RBRACK,
  [1260] = 3,
    ACTIONS(359), 1,
      anon_sym_LF,
    ACTIONS(361), 1,
      anon_sym_SEMI,
    ACTIONS(381), 1,
      anon_sym_RBRACK,
  [1270] = 3,
    ACTIONS(359), 1,
      anon_sym_LF,
    ACTIONS(361), 1,
      anon_sym_SEMI,
    ACTIONS(383), 1,
      anon_sym_RBRACK,
  [1280] = 3,
    ACTIONS(359), 1,
      anon_sym_LF,
    ACTIONS(361), 1,
      anon_sym_SEMI,
    ACTIONS(385), 1,
      anon_sym_RBRACK,
  [1290] = 3,
    ACTIONS(365), 1,
      anon_sym_LF,
    ACTIONS(367), 1,
      anon_sym_SEMI,
    ACTIONS(387), 1,
      ts_builtin_sym_end,
  [1300] = 2,
    ACTIONS(371), 1,
      anon_sym_SEMI,
    ACTIONS(369), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1308] = 1,
    ACTIONS(389), 2,
      sym__word_content,
      sym_escape_sequence,
  [1313] = 1,
    ACTIONS(391), 2,
      sym__word_content,
      sym_escape_sequence,
  [1318] = 2,
    ACTIONS(359), 1,
      anon_sym_LF,
    ACTIONS(361), 1,
      anon_sym_SEMI,
  [1325] = 2,
    ACTIONS(365), 1,
      anon_sym_LF,
    ACTIONS(367), 1,
      anon_sym_SEMI,
  [1332] = 1,
    ACTIONS(393), 2,
      sym__word_content,
      sym_escape_sequence,
  [1337] = 1,
    ACTIONS(395), 1,
      anon_sym_RBRACE,
  [1341] = 1,
    ACTIONS(397), 1,
      anon_sym_RBRACE,
  [1345] = 1,
    ACTIONS(399), 1,
      aux_sym__simple_variable_substitution_token1,
  [1349] = 1,
    ACTIONS(401), 1,
      ts_builtin_sym_end,
  [1353] = 1,
    ACTIONS(403), 1,
      aux_sym__simple_variable_substitution_token1,
  [1357] = 1,
    ACTIONS(405), 1,
      aux_sym__simple_variable_substitution_token1,
  [1361] = 1,
    ACTIONS(407), 1,
      aux_sym__simple_variable_substitution_token1,
  [1365] = 1,
    ACTIONS(409), 1,
      anon_sym_RBRACE,
  [1369] = 1,
    ACTIONS(411), 1,
      aux_sym__braced_variable_substitution_token1,
  [1373] = 1,
    ACTIONS(413), 1,
      anon_sym_RBRACE,
  [1377] = 1,
    ACTIONS(415), 1,
      aux_sym__braced_variable_substitution_token1,
  [1381] = 1,
    ACTIONS(417), 1,
      aux_sym__braced_variable_substitution_token1,
  [1385] = 1,
    ACTIONS(419), 1,
      aux_sym__braced_variable_substitution_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(26)] = 0,
  [SMALL_STATE(27)] = 21,
  [SMALL_STATE(28)] = 42,
  [SMALL_STATE(29)] = 63,
  [SMALL_STATE(30)] = 84,
  [SMALL_STATE(31)] = 105,
  [SMALL_STATE(32)] = 126,
  [SMALL_STATE(33)] = 147,
  [SMALL_STATE(34)] = 168,
  [SMALL_STATE(35)] = 189,
  [SMALL_STATE(36)] = 210,
  [SMALL_STATE(37)] = 231,
  [SMALL_STATE(38)] = 252,
  [SMALL_STATE(39)] = 268,
  [SMALL_STATE(40)] = 284,
  [SMALL_STATE(41)] = 300,
  [SMALL_STATE(42)] = 316,
  [SMALL_STATE(43)] = 344,
  [SMALL_STATE(44)] = 360,
  [SMALL_STATE(45)] = 376,
  [SMALL_STATE(46)] = 404,
  [SMALL_STATE(47)] = 432,
  [SMALL_STATE(48)] = 448,
  [SMALL_STATE(49)] = 464,
  [SMALL_STATE(50)] = 480,
  [SMALL_STATE(51)] = 496,
  [SMALL_STATE(52)] = 524,
  [SMALL_STATE(53)] = 539,
  [SMALL_STATE(54)] = 554,
  [SMALL_STATE(55)] = 579,
  [SMALL_STATE(56)] = 604,
  [SMALL_STATE(57)] = 629,
  [SMALL_STATE(58)] = 648,
  [SMALL_STATE(59)] = 663,
  [SMALL_STATE(60)] = 682,
  [SMALL_STATE(61)] = 697,
  [SMALL_STATE(62)] = 712,
  [SMALL_STATE(63)] = 727,
  [SMALL_STATE(64)] = 742,
  [SMALL_STATE(65)] = 757,
  [SMALL_STATE(66)] = 772,
  [SMALL_STATE(67)] = 791,
  [SMALL_STATE(68)] = 806,
  [SMALL_STATE(69)] = 821,
  [SMALL_STATE(70)] = 836,
  [SMALL_STATE(71)] = 855,
  [SMALL_STATE(72)] = 874,
  [SMALL_STATE(73)] = 893,
  [SMALL_STATE(74)] = 907,
  [SMALL_STATE(75)] = 921,
  [SMALL_STATE(76)] = 935,
  [SMALL_STATE(77)] = 949,
  [SMALL_STATE(78)] = 963,
  [SMALL_STATE(79)] = 977,
  [SMALL_STATE(80)] = 991,
  [SMALL_STATE(81)] = 1004,
  [SMALL_STATE(82)] = 1023,
  [SMALL_STATE(83)] = 1036,
  [SMALL_STATE(84)] = 1049,
  [SMALL_STATE(85)] = 1062,
  [SMALL_STATE(86)] = 1081,
  [SMALL_STATE(87)] = 1094,
  [SMALL_STATE(88)] = 1107,
  [SMALL_STATE(89)] = 1126,
  [SMALL_STATE(90)] = 1137,
  [SMALL_STATE(91)] = 1148,
  [SMALL_STATE(92)] = 1159,
  [SMALL_STATE(93)] = 1170,
  [SMALL_STATE(94)] = 1181,
  [SMALL_STATE(95)] = 1192,
  [SMALL_STATE(96)] = 1202,
  [SMALL_STATE(97)] = 1212,
  [SMALL_STATE(98)] = 1220,
  [SMALL_STATE(99)] = 1230,
  [SMALL_STATE(100)] = 1240,
  [SMALL_STATE(101)] = 1250,
  [SMALL_STATE(102)] = 1260,
  [SMALL_STATE(103)] = 1270,
  [SMALL_STATE(104)] = 1280,
  [SMALL_STATE(105)] = 1290,
  [SMALL_STATE(106)] = 1300,
  [SMALL_STATE(107)] = 1308,
  [SMALL_STATE(108)] = 1313,
  [SMALL_STATE(109)] = 1318,
  [SMALL_STATE(110)] = 1325,
  [SMALL_STATE(111)] = 1332,
  [SMALL_STATE(112)] = 1337,
  [SMALL_STATE(113)] = 1341,
  [SMALL_STATE(114)] = 1345,
  [SMALL_STATE(115)] = 1349,
  [SMALL_STATE(116)] = 1353,
  [SMALL_STATE(117)] = 1357,
  [SMALL_STATE(118)] = 1361,
  [SMALL_STATE(119)] = 1365,
  [SMALL_STATE(120)] = 1369,
  [SMALL_STATE(121)] = 1373,
  [SMALL_STATE(122)] = 1377,
  [SMALL_STATE(123)] = 1381,
  [SMALL_STATE(124)] = 1385,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(109),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(30),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(30),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(117),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(124),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(54),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(5),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, .production_id = 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, .production_id = 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(110),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word_list, 1),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word_list, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(37),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(114),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(120),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(56),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(19),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(8),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(30),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(117),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(124),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(54),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(21),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(5),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(71),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(116),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(123),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(55),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(25),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(14),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(107),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_concatenation_repeat1, 2),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2), SHIFT_REPEAT(81),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concatenation, 2),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_concatenation, 2),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 2),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 2),
  [230] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 2), SHIFT(108),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 1), SHIFT(107),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__word, 1),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__word, 1),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(108),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 2), SHIFT(107),
  [252] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2), SHIFT_REPEAT(85),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 1), SHIFT(108),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_substitution, 1),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_substitution, 1),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__braced_variable_substitution, 3),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__braced_variable_substitution, 3),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [268] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2, .dynamic_precedence = 1),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2, .dynamic_precedence = 1),
  [282] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [284] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(46),
  [287] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(118),
  [290] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(122),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2),
  [295] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(46),
  [298] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(12),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_variable_substitution, 2),
  [303] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_variable_substitution, 2),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 4),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 4),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 3),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 3),
  [315] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [323] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_word, 2),
  [331] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_word, 2),
  [333] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(111),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 2),
  [338] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 2),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_word, 3),
  [342] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_word, 3),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_word, 3),
  [346] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_word, 3),
  [348] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_concatenation_repeat1, 2), SHIFT_REPEAT(88),
  [351] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 1), SHIFT(111),
  [354] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_word, 2), SHIFT(111),
  [357] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [361] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [363] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [367] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, .production_id = 2),
  [371] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, .production_id = 2),
  [373] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [375] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [377] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [379] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [381] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [383] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [385] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [387] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [401] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_tcl_external_scanner_create(void);
void tree_sitter_tcl_external_scanner_destroy(void *);
bool tree_sitter_tcl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_tcl_external_scanner_serialize(void *, char *);
void tree_sitter_tcl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tcl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_tcl_external_scanner_create,
      tree_sitter_tcl_external_scanner_destroy,
      tree_sitter_tcl_external_scanner_scan,
      tree_sitter_tcl_external_scanner_serialize,
      tree_sitter_tcl_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
